### ISSUE TITLE
`__webpack_require__(null)` when using manual splitChunks, concatenateModules

### ISSUE THREAD

**Issue by Knagis** [webpack/webpack#11856]
# Bug report

**What is the current behavior?**

This might be closely related to #11770. 

```
// EXTERNAL MODULE: ./packages/path/SomeModule.ts
var SomeModule = __webpack_require__(null);
```

obviously moduleId null does not work... This module is one that is extracted into a common chunk as part of concatenated module with some ID like 784404 - an ID that is not referenced anywhere at all.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduces in our huge monorepo, so far no luck in creating a small reproduction. Even in our repo, building just the parts affected do not reproduce it, only building everything (~40 entries) produces the error.

Some notes:
* reproduces in production mode
* building with `devTool: false`.
* setting `innerGraph: false` *does not* affect the issue.
* setting `concatenateModules: false` "fixes" the issue
* setting `usedExports: "global"` also "fixes" the issue

**What is the expected behavior?**

Correctly generated chunks with no missing modules.

Btw, `moduleId: null` if it does happen, should perhaps throw during build since it will never work at runtime.

**Other relevant information:**
webpack version:  5.3.0
Node.js version: 12.13.1
Operating System: any
Additional tools:

**Comment by Knagis** [comment]
`usedExports: "global"` also prevents the issue

**Comment by sokra** [comment]
Hmm yes that really sounds related to that. To me it sounds like a bug in the module concatenation, especially the algorithm that selects which modules are concatenated. Probably related to the runtime filtering. I have one idea which I can try to figure out how to reproduce it (note to myself: entry A -> c -> d, entry B -> d, c and d force to chunk, c + d concatenated, maybe c -> d conditional).

**Comment by sokra** [comment]
Ok I found something. Looks really like your issue. I'm pretty sure https://github.com/webpack/webpack/pull/11861 fixes your issue, but it would be great if you could test it in your codebase.

```
"webpack": "webpack/webpack#bugfix/11856
```

**Comment by Knagis** [comment]
Yes, just tested and this issue is fixed in the branch.

**Comment by YikaJ** [comment]
webpack^5.24.4 still get this problem

![image](https://user-images.githubusercontent.com/8725110/113966327-7b21e280-9861-11eb-8e64-e316565b33a1.png)

**Comment by paradite** [comment]
same issue here with `webpack@5.31.2`, `concatenateModules: false` did help to fix the issue.
we are doing a re-export of modules if that helps.

**Comment by zdila** [comment]
I've just migrated our project from webpack 4 to webpack 5 and also experience this issue. Referenced `null` module is not instructed to be a chunk. It constains a single object that is default-exported:

```
export default {
   // some properties
}
```

Removing `new webpack.optimize.ModuleConcatenationPlugin()` fixed the problem.
