### ISSUE TITLE
[Webpack 5 custom plugin upgrade question] PluginHelper.addParsedVariableToModule Substitute

### ISSUE THREAD

**Issue by janlent1** [webpack/webpack#11974]
# Webpack 5 Question

**What is the current behavior?**
I would like to upgrade our repo to webpack5. We have custom plugins. In webpack4, the plugin just could be added without issues. Now though, webpack code doesnt inlcude the ParserHelper.addParsedVariableToModule anymore, so that is now changed. Therefore I would like to get some information about how I could make this work with the webpack 5 code(some new dependency or other ways?).
[Here](https://github.com/GoogleChromeLabs/worker-plugin/issues/88#issuecomment-688568600) they talk about the replacement for this parser helper function. In the old way, you could set addParsedVariableToModule(parser,name,expression). How can i do that with the new way mentioned above?
I have to give a special expression to the expression argument, which sets a custom method there which extends webpack_require...

Below is the code that I basically want to adapt to make work in webpack 5. This is called in a tap.for when there is a certain require call noticed. So the access to the parser is given.

```
ParserHelpers.addParsedVariableToModule(
    parser,
    'CustomPluginFor' + Name.replace(/[.]/g, '_'),
    `__webpack_require__.map.set('${Name}', require.resolve(` +
    JSON.stringify(resPath + '.specialending') +
    '))'
)
```

**What is the expected behavior?**
I would like to be able to add this logic to the modules that I tap into. This is a basic hook tap into the function code that is nothing crazy. All the variables are available and given. I need advice to find another way how to achieve what I did in webpack 5 such as using a dependency that does said thing or some other advice that will let me understand how to fix my issue.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 12.17.10
Operating System: MacOS

**Comment by sokra** [comment]
These feature has been removed. The new way to do that is to use a (custom) Dependency, which adds a `InitFragment` in its DependencyTemplate.

As example look at webpack/lib/dependencies/CachedConstDependency.

**Comment by janlent1** [comment]
Dankeschoen! Yeah I'll try the CachedConstDependency and will give you feedback!

**Comment by janlent1** [comment]
@sokra the addParsedVariableToModule returned false if it couldnt add the variable or fails to do it... Is there now a way to check for that or will it just create a build error itself? Or does one notice that only during runtime?

**Comment by janlent1** [comment]
@sokra, the require.resolve as mentioned above is also not resolvable with the runtimerequirements.add runtime.globals requireScope... Do you have an idea how to add that?

**Comment by janlent1** [comment]
So that would mean a custom kind of mix between requireresolvedependency and the cachedconstdependency as well as the moduledependencytemplateasid....

**Comment by janlent1** [comment]
@sokra, i tried adding the 
```
const content = runtimeTemplate.moduleId({
			module: moduleGraph.getModule(dep),
			chunkGraph,
			request: dep.request,
			weak: dep.weak
		});
```
To the custom template to require the module that i need in the other custom dependencies template,
and so i created something like this:
```
In custom dependencytemplate:

const content = runtimeTemplate.moduleId({
			module: moduleGraph.getModule(/** @type {ModuleDependency} */  (new RequireResolveDependency("/absolute/path/to/file.js")))// moduleGraph.getModule(dep),
			chunkGraph,
			request: '/absoulte/path/to/file.js',
			weak: dep.weak
		});
```
But i always return null... I cannot seem to find the module.. Do I need to add that in the constructor of the custom dependency or where should i do that?

**Comment by janlent1** [comment]
@sokra , i adapted the custom dependency to be more of a require resolve dependency-customization with the cachedconstdependency capabilites in the template. Still I dont get any module when i get ot the code from above.... Do you have any idea why?

**Comment by sokra** [comment]
You can only call moduleGraph.getModule on dependencies that were resolved. Best pass yourself into it (`dependency` argument of the template) assuming you are a subclass of ModuleDependency.

**Comment by janlent1** [comment]
@sokra, this is what I thought about as well and already did. So maybe my resolving is not right... I will check it again and give feedback. Thanks for the answer.

**Comment by janlent1** [comment]
@sokra it still doesnt resolve somehow even thought the absolute path to the file is correct... do i maybe need to put a relative request? When I am putting the absolute path, I cannot get the module...And what about file ending? so Should i remove the .js or not?
I also didnt use addpresentataionaldependency but adddependency, as it is a moduledependency.. Do you happen to have any idea where the issue might lie?
Thanks!

**Comment by janlent1** [comment]
Is the userrequest different from the request in the dependency?

**Comment by janlent1** [comment]
I also havent added those functions from the requireresolvedependency:
	```
get type() {
		return "require.resolve";
	}

	get category() {
		return "commonjs";
	}

	/**
	 * Returns list of exports referenced by this dependency
	 * @param {ModuleGraph} moduleGraph module graph
	 * @param {RuntimeSpec} runtime the runtime for which the module is analysed
	 * @returns {(string[] | ReferencedExport)[]} referenced exports
	 */
	getReferencedExports(moduleGraph, runtime) {
		// This doesn't use any export
		return Dependency.NO_EXPORTS_REFERENCED;
	}
```
Those dont make a difference though right?

**Comment by janlent1** [comment]
@sokra, argh i didnt add the 
```
compilation.dependencyFactories.set(
                customdependency,
                normalModuleFactory
            );
```
Now it is concatinating the custom identifiers for the variables..
I will take a look at that tomorrow and will give further feedback.
Greetings!

**Comment by janlent1** [comment]
@sokra, I think i just solved the issue, I just wanted to inject some variables not replace anythign, so I removed the source.replace coding and left the initfragment stuff. What I dont see in teh output though is that the surrounding function block has a __wepack_require__ included even though I added the _runtimeRequirements_. 
This was before in the surrounding block:
`/***/ (function(module, exports, __webpack_require__) {`
This is now in the surrounding block:
`(() => {`
What should I add where so this is added?

**Comment by janlent1** [comment]
@sokra now im having the issue, that the module cannot be found:
it seems to be because im giving the full path, but the resolver looks relative to the current path we are in.... Is there a way to tell the resolver to not resolve inside the current subfolder?

**Comment by evilebottnawi** [comment]
Please stop spamming, it is not stackoverflow, it is bug tracker, if you want an answer, ask that and a clear question, I am closing this issue, because not problems with webpack here, anyway you can continue ask some questions here

**Comment by janlent1** [comment]
@evilebottnawi sorry for spamming. Thanks for the help @sokra, I think I fixed the questions I had.
But don't think I would have gotten the answers I got here on stackoverflow.

**Comment by janlent1** [comment]
Now I have the issue of Uncaught (in promise) TypeError: Cannot read property 'call' of undefined because the module that I require with the InitFragment is not including the actual module in the chunk

**Comment by evilebottnawi** [comment]
include it

**Comment by janlent1** [comment]
@evilebottnawi 
Well in the previous implementation the custom require.resolve looked in the webpack build file something like this:
`/*require.resolve*/(1)`
I thought one needs to add something like this though:
`__webpack_require__(1)`
But that didn't seem to work, so now instead of adding __webpack_require__() to the initfragment surrounding the resolved module id that i wanted to resolve with resolve.require, I added the code that was added before:
`/*require.resolve*/(1)`
That seems to still work in webpack 5. I will run some tests and see whether that will work now.

**Comment by janlent1** [comment]
@alexander-akait I now want my custom dependency to be cacheable. I added the makeSerializable method and when I register the custom class, it is added to the serializers map. But when it is reading from it in the getSerializerFor method, then the map entry is gone. Then it also cannot serializer and throws warnings. What could that be? Do you happen to know that? Did it get sorted out because of some false information or why could the map not have the custom class that was previously added?
Thanks and Best,
Jan
