### ISSUE TITLE
Cache breaks asset module live reloading

### ISSUE THREAD

**Issue by stefan-toubia** [webpack/webpack#13275]
# Bug report

**What is the current behavior?**
Live reloading breaks for assets using `asset/resource` rule type when caching is enabled.

**If the current behavior is a bug, please provide the steps to reproduce.**

Add an asset loader rule:
```
      {
        test: /\.(png|svg|jpg|jpeg|gif)$/i,
        type: "asset/resource",
      },
```

Import an asset
```tsx
import React from "react";
import ReactDOM from "react-dom";
import logoSrc from "./assets/logo.png";

import "./styles.less";

const App = (): JSX.Element => (
  <div>
    <img src={logoSrc} alt="logo" />
    <div>Hello, React!</div>
  </div>
);

ReactDOM.render(<App />, document.getElementById("root"));

```

The initial page load works as expected.
Commenting out the `img` and/or import, then reverting causes the image asset to be not found.

```sh
$ curl http://localhost:9009/assets/logo-ff7cf555f3ab2107e716.png
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /assets/logo-120x120@2x-ff7cf555f3ab2107e716.png</pre>
</body>
</html>
```

Disabling the cache "fixes" the issue

```js
// webpack.config.js
module.exports = {
  ...
  cache: false,
  ...
}
```

It's also not an issue when using `asset/inline`.

[webpack.config.js](https://gist.github.com/stefan-toubia/ec80025f1e2e86c82feb6117a5c120f5)

**What is the expected behavior?**
I know "it should work" is not helpful, but it seems self explanatory here.

**Other relevant information:**
webpack version:  5.36.1
Node.js version: 10.24.1
Operating System: OS X 10.14.6
Additional tools:

**Comment by sokra** [comment]
Do you have `output.clean: true` or some other cleaning plugin in config?

**Comment by sokra** [comment]
Might be fixed by #13276

**Comment by stefan-toubia** [comment]
Yes, I'm using `output.clean` and confirmed that asset reloading works as expected when `clean` is disabled. For now I can turn `clean` off in development.

**Comment by sokra** [comment]
This should be fixed in the latest version

**Comment by alexander-akait** [comment]
Confirmed, fixed by https://github.com/webpack/webpack/releases/tag/v5.36.2, the same issue https://github.com/webpack/webpack-dev-server/issues/3175#issuecomment-817160236, let's close, feel free to feedback

**Comment by alexilin83** [comment]
It seems that bug still exists. I'm using webpack 5.57.1 and with output.clean = true image assets not fount after hot reload.

**Comment by alexander-akait** [comment]
Please provide reproducible test repo

**Comment by alexilin83** [comment]
> 
> 
> Please provide reproducible test repo

https://github.com/alexilin83/webpack_test_image

**Comment by sokra** [comment]
@jantimon This is related to the caching in html-webpack-plugin. `output.clean` removes all files that are not emitted as `compilation.assets`. html-webpack-plugin need to make sure to always put their assets into `compilation.assets` even when cached.

**Comment by alexander-akait** [comment]
@alexilin83 Workaround -  `cache: false` for `html-webpack-plugin`

**Comment by alexander-akait** [comment]
hm, weird, looks like it is not real disable cache, anyway we can't fix it here

**Comment by alexander-akait** [comment]
@jantimon here repo https://github.com/alexilin83/webpack_test_image, check this

**Comment by alexander-akait** [comment]
To fix this:

in `child-compier.js`

```js
result[this.templates[entryIndex]] = {
  content: templateSource,
  hash: childCompilation.hash || 'XXXX',
  entry: entries[entryIndex],
  assets: childCompilation.assets,
};
```

`index.js`
```js
if (isCompilationCached && options.cache && assetJson === newAssetJson) {
  previousEmittedAssets.forEach(({ name, html, source }) => {
    compilation.emitAsset(name, source ? source : new webpack.sources.RawSource(html, false));
  });
  return callback();
  } else {
    previousEmittedAssets = [];
    assetJson = newAssetJson;
}

// ...
// ...
// ...

const replacedFilename = replacePlaceholdersInFilename(filename, html, compilation);
// Add the evaluated html code to the webpack assets
compilation.emitAsset(replacedFilename.path, new webpack.sources.RawSource(html, false), replacedFilename.info);
previousEmittedAssets.push({ name: replacedFilename.path, html });
              
Object.keys(templateResult.compiledEntry.assets).forEach((name) => {
  const source = templateResult.compiledEntry.assets[name];

  previousEmittedAssets.push({ name: name, source });
})
              
return replacedFilename.path;
```

Note - it is simple fix and not full, you **should** keep `assetsInfo` and re in `emitAsset`, also it is fix only `cache: true`, logic is still broken for `cache: false`, but you can use the same approach (i.e. `previousEmittedAssets = []` replace on logic for `cache: true`), also note - assets can be changed and you should invalidate cache own cache too, the main problem - you should not use custom caching, webpack already has great built-in cache API. Also I don't understand why do you use loader for cache, it is really weird and decrease perf and memory usage, you need just static function (provided by developer) and use it, or you can create own `Module` (like we do in `mini-css-extract-plugin` - `CssModules`) and no problems with cache anymore.

A while ago I asked you to move repo inside `webpack-contrib` so it will be already implemented and works fine, but for some reason you didn’t want it :thinking:
