### ISSUE TITLE
Hot only HMR failed to work in 5.48.0

### ISSUE THREAD

**Issue by otakustay** [webpack/webpack#13930]
# Bug report

**What is the current behavior?**

HMR fails to work

**If the current behavior is a bug, please provide the steps to reproduce.**

Open [x.zip](https://github.com/webpack/webpack/files/6937822/x.zip) and follow reproduce steps in `README.md`

**What is the expected behavior?**

HMR should work to update browser content.

According to #12408 , HMR check api fails to add updated modules to `updatedModuleList` array, and with the change in 551f64a59030c9250fdf97ce05b49d98efb45dab it adds an empty array check, now HMR failed to work completely.

Dowgrade webpack to 5.47.0 can solve this issue.

**Other relevant information:**

webpack version:  5.48.0
Node.js version: v16.5.0
Operating System: macOS
Additional tools: No

**Comment by Jack-Works** [comment]
Having this problem too. Minimal reproduce:

> package.json

```json
{
  "dependencies": {
    "html-webpack-plugin": "^5.3.2",
    "webpack": "^5.48.0",
    "webpack-cli": "^4.7.2"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.11.2"
  }
}
```

> webpack.config.js

```js
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
    output: {
        path: __dirname + '/dist',
        filename: 'index_bundle.js'
    },
    plugins: [
        new HtmlWebpackPlugin()
    ],
    devServer: {
        hot: true,
        hotOnly: true,
    }
}
```

> src/index.js

```js
import.meta.webpackHot?.accept('./run.js', () => {
    import('./run').then(x => console.log('HMR', x.a))
})
import('./run').then(x => console.log(x.a))
```

> src/run.js

```js
export const a = 234
```


Run `npm install`, then `npx webpack serve --mode development`. Change run.js

```
[HMR] Cannot find update. Need to do a full reload!
[HMR] (Probably because of restarting the webpack-dev-server)

**Comment by alexander-akait** [comment]
Remove `hotOnly`, using:
```
hot: true,
hotOnly: true,
```

is wrong

**Comment by otakustay** [comment]
Yes, this is just introduced when I was debugging, in practice only hotOnly is used, this issue however isn't affected by this

**Comment by Jack-Works** [comment]
> Remove `hotOnly` and keep only `hot: true`, using:
> 
> ```
> hot: true,
> hotOnly: true,
> ```
> 
> is wrong

Without `hotOnly` it will refresh the page (IIRC). Refresh the page isn't "hot module reload"

**Comment by alexander-akait** [comment]
@Jack-Works you should use `hot` or `hotOnly`, not both, in webpack-dev-server v4, hotOnly was removed in favor `hot: boolean | 'only'`

**Comment by Jack-Works** [comment]
> @Jack-Works you should use `hot` or `hotOnly`, not both, in webpack-dev-server v4, `hotOnly` was removed in favor `hot: boolean | 'only'`

Oh yes, remove `hotOnly` to solve the problem in my minimal show case. But downgrade to 5.47.0 with both `hot` and `hotOnly` also fix the problem. And I didn't see any warning/something like that to notice me `hot` and `hotOnly` cannot be used in the same time.

**Comment by alexander-akait** [comment]
Fix for original issue here https://github.com/webpack/webpack/pull/13932

**Comment by alexander-akait** [comment]
@Jack-Works it was in docs and also fixed in v4, just remove `hot` or `hotOnly`

**Comment by otakustay** [comment]
Leaving `hotOnly: true` still reproduce the problem, HMR isn't working in hot-only mode, not sure the motivation #13932 adds that empty array check

**Comment by otakustay** [comment]
Yes I read that comment, but still, from the referenced issue it says "its a bugfix" but I still didn't find the detail of bug. To be clear, if that issue is revert-able, I'm willing to open a PR to revert that change.

**Comment by alexander-akait** [comment]
Fix above, before we have invalid fix, just wait merge and release

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/13932
