### ISSUE TITLE
__dirname and __filename should not be provided for target: web

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#14229]
# Bug report

Similar https://github.com/webpack/webpack/issues/14072, you will find the same for `console.log(__filename);` and `console.log(__dirname)`, but no these variables in browser, yes bug, it should be not handled for ECMA modules and not handled for `target: web` (should throw a warning, because error will be breaking change), feel free to feedback

_Originally posted by @alexander-akait in https://github.com/webpack/webpack/issues/14210#issuecomment-917419144_

**What is the current behavior?**

__dirname and __filename are mocked

**If the current behavior is a bug, please provide the steps to reproduce.**

`console.log(__filename)` 

**What is the expected behavior?**

add a warning on usage

**Other relevant information:**
webpack version:  5
Node.js version: 
Operating System: 
Additional tools:

**Comment by vankop** [comment]
fixed

**Comment by alexander-akait** [comment]
Not fixed, look at here https://github.com/webpack/webpack/pull/14247

**Comment by vankop** [comment]
this issue about warning..

**Comment by alexander-akait** [comment]
Oh, yes, my mistake :+1:
