### ISSUE TITLE
jest-worker 27.4.0 breaks webpack builds with node options

### ISSUE THREAD

**Issue by MirKml** [webpack/webpack#14859]
# Bug report

When latest webpack is used with latest jest - 27.4.0, it breaks production builds with custom node options. e.g. 
`node --max_old_space_size=2768 node_modules/webpack-cli/bin/cli.js --mode production`

Result is
```
ERROR in 497.a3d1.js from Terser
Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --max_old_space_size=2768
    at new NodeError (internal/errors.js:322:7)
    at new Worker (internal/worker.js:196:13)
    at ExperimentalWorker.initialize (/permissions/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
    at new ExperimentalWorker (/permissions/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:10)
    at WorkerPool.createWorker (/permissions/node_modules/jest-worker/build/WorkerPool.js:44:12)
    at new BaseWorkerPool (/permissions/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:27)
    at new WorkerPool (/permissions/node_modules/jest-worker/build/WorkerPool.js:30:1)
    at new Worker (/permissions/node_modules/jest-worker/build/index.js:167:26)
    at getWorker (/permissions/node_modules/terser-webpack-plugin/dist/index.js:288:9)
    at /permissions/node_modules/terser-webpack-plugin/dist/index.js:389:41
```

Problem is with latest jest-worker.
There is installed tree with npm
```
$ npm ls jest-worker
permissions@1.0.0 ./src
├─┬ babel-jest@27.4.0
│ └─┬ @jest/transform@27.4.0
│   └─┬ jest-haste-map@27.4.0
│     └── jest-worker@27.4.0 deduped
├─┬ jest@27.4.0
│ └─┬ @jest/core@27.4.0
│   ├─┬ @jest/reporters@27.4.0
│   │ └── jest-worker@27.4.0 deduped
│   └─┬ jest-runner@27.4.0
│     └── jest-worker@27.4.0 deduped
└─┬ webpack@5.64.4
  └─┬ terser-webpack-plugin@5.1.4
    └── jest-worker@27.4.0
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Install latest webpack with latest jest
Use some simple webpack config which utilizes production build. I can try it later for minimal setup if necessary.

**What is the expected behavior?**

Production builds work as expected. Lowering jest-worker dependency can be solution.

**Other relevant information:**
webpack version:  5.64.4
Node.js version:  16.13.0
Operating System: Windows, Linux
Additional tools: jest@27.4.0

**Comment by timoschlueter** [comment]
I can confirm this broke our pipelines today. We fixed it with the workaround from @MirKml.
Not perfect, but works for now. Thank you!

**Comment by alexander-akait** [comment]
Fixed https://github.com/facebook/jest/releases/tag/v27.4.1, please update jest

**Comment by anagh416** [comment]
after this fix has been moved , I m getting this error (from 29th Nov)
the jest-worker I have is 27.4.2  seems like related to this fix
21:57:38  ERROR in 319.0a46e60283f8bec09734.manager.bundle.js from Terser
21:57:38  Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid NODE_OPTIONS env variable: --max-http-header-size= is not allowed in NODE_OPTIONS
21:57:38      at new Worker (internal/worker.js:164:13)
21:57:38      at ExperimentalWorker.initialize (/bld/workspace/_Pipeline2_NX_Upgrade_forCypress@2/flex/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
21:57:38      at new ExperimentalWorker (/bld/workspace/_Pipeline2_NX_Upgrade_forCypress@2/flex/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:10)
21:57:38      at WorkerPool.createWorker (/bld/workspace/_Pipeline2_NX_Upgrade_forCypress@2/flex/node_modules/jest-worker/build/WorkerPool.js:44:12)
21:57:38      at new BaseWorkerPool (/bld/workspace/_Pipeline2_NX_Upgrade_forCypress@2/flex/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:27)
2

**Comment by kelly-tock** [comment]
I tried latest jest, did not fix the issue.

**Comment by kelly-tock** [comment]
suggested workaround did not work either. getting this:

```
Initiated Worker with invalid execArgv flags: --max-old-space-size=4096
Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --max-old-space-size=4096
    at new NodeError (internal/errors.js:322:7)
    at new Worker (internal/worker.js:196:13)
    at ExperimentalWorker.initialize (/Users/kelly/tock/admin/consumer/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:149:20)
    at new ExperimentalWorker (/Users/kelly/tock/admin/consumer/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/workers/NodeThreadsWorker.js:145:10)
    at WorkerPool.createWorker (/Users/kelly/tock/admin/consumer/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/WorkerPool.js:44:12)
    at new BaseWorkerPool (/Users/kelly/tock/admin/consumer/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/base/BaseWorkerPool.js:127:27)
    at new WorkerPool (/Users/kelly/tock/admin/consumer/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/WorkerPool.js:30:1)
    at new Worker (/Users/kelly/tock/admin/consumer/node_modules/terser-webpack-plugin/node_modules/jest-worker/build/index.js:167:26)
    at getWorker (/Users/kelly/tock/admin/consumer/node_modules/terser-webpack-plugin/dist/index.js:391:9)
    at /Users/kelly/tock/admin/consumer/node_modules/terser-webpack-plugin/dist/index.js:494:41
```

**Comment by kelly-tock** [comment]
running the command via yarn script:
```
"webpack_client_prod": "NODE_ENV=production npx -n '--max-old-space-size=4096' -n '--trace-deprecation' webpack --color --config ./webpack/webpack.config.prod.client.js",
```

**Comment by MirKml** [comment]
In mentioned jest PR which fixed issue, there is discussion about underscores, dashes. Maybe it helps you.

My mentioned node option --max_old_space_size is fixed.

**Comment by alexander-akait** [comment]
Even time when you write - `Not fixed`, please use `npm ls jest-worker`, and double check you have update version

**Comment by alexander-akait** [comment]
Please open an issue in `jest` repo

**Comment by DzmVasileusky** [comment]
@anagh416 @kelly-tock 

They are already working on it
