### ISSUE TITLE
Dynamic expression imports are broken on Typescript 4.9.2 and higher

### ISSUE THREAD

**Issue by jsprw** [webpack/webpack#16793]
# Bug report

**What is the current behavior?**

I have encountered the same issue since upgrading to Typescript 4.9.5 with a issue that looks the same as the one discussed here: https://github.com/webpack/webpack/discussions/16566.

It looks like Typescript 4.9.2+ changed the code that it emits for dynamic imports: the import path is assigned to a variable (see https://github.com/microsoft/TypeScript/issues/51554) prior to passing it to the import() function. Therefore Webpack does not seem to understand what to import and emits `Critical dependency: the request of a dependency is an expression` warnings. Before v4.9.2 it does not emit any warnings and it works fine.

What's emitted by Typescript 4.9.5:
```
await Promise.all(filesToImport.map((e) => { var _a; return _a = `./relative/path/to/files/${e}`, Promise.resolve().then(() => tslib_1.__importStar(__webpack_require__("./path/of/app sync recursive")(_a))); }))
```

What's emitted by Typescript 4.9.1-beta (and earlier) with the same project and Webpack configuration:
```
await Promise.all(filesToImport.map((e) => Promise.resolve().then(() => tslib_1.__importStar(__webpack_require__("./relative/path/to/files sync recursive ^\\.\\/.*$")(`./${e}`)))))
```

The solution for me is to use Typescript 4.9.1-beta for the time-being, I tried using the dynamic import magic comments but they don't seem to influence much either.

**If the current behavior is a bug, please provide the steps to reproduce.**

Created a reproduction repo here: https://github.com/jsprw/webpack-typescript495.

Use the following npm scripts to reproduce the error (it will set the correct Typescript version in the script):

- Working fine on Typescript@4.9.1-beta: `npm run typescript-4.9.1-beta`
- Broken on Typescript@latest `npm run typescript-latest`

**What is the expected behavior?**

The expected behavior is seen with Typescript version 4.9.1-beta (`npm run typescript-4.9.1-beta`).

**Other relevant information:**
webpack version:  5.76.0
Node.js version: v16.15.0
Operating System: MacOS Ventura
Additional tools: Typescript 4.9.5

**Comment by dazjean** [comment]
+1

**Comment by alexander-akait** [comment]
Sorry we can't solve it here, because it is not statical analizable code (you will have the same error in all bundler), look that typescript emits:

**4.9.5**

```ts
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
(function () {
    return __awaiter(this, void 0, void 0, function* () {
        const files = ["import1.ts", "import2.ts", "import3.ts"];
        const imports = yield Promise.all(files.map((file) => { var _a; return _a = `./dynamic-imports/${file}`, Promise.resolve().then(() => __importStar(require(_a))); }));
        // this should log an array of objects
        // in typescript 4.9.5 on node v16.15.0, this will throw an MODULE_NOT_FOUND error
        console.log(imports);
    });
})();
```
**before**:
```ts
"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
(function () {
    return __awaiter(this, void 0, void 0, function* () {
        const files = ["import1.ts", "import2.ts", "import3.ts"];
        const imports = yield Promise.all(files.map((file) => Promise.resolve().then(() => __importStar(require(`./dynamic-imports/${file}`)))));
        // this should log an array of objects
        // in typescript 4.9.5 on node v16.15.0, this will throw an MODULE_NOT_FOUND error
        console.log(imports);
    });
})();

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IMPORT1 = void 0;
exports.IMPORT1 = "IMPORT1";

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IMPORT2 = void 0;
exports.IMPORT2 = "IMPORT2";

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IMPORT3 = void 0;
exports.IMPORT3 = "IMPORT3";
```

We can't analize:
```js
const imports = yield Promise.all(files.map((file) => { var _a; return _a = `./dynamic-imports/${file}`, Promise.resolve().then(() => __importStar(require(_a))); }));
```

but before it works good:
```ts
const imports = yield Promise.all(files.map((file) => Promise.resolve().then(() => __importStar(require(`./dynamic-imports/${file}`)))));
```

**Comment by alexander-akait** [comment]
Looks like it was changed only for `commonjs`, because if you use `esnext`, all works fine...

**Comment by DanielRosenwasser** [comment]
Is there any reason why using `--module esnext` and `--moduleResolution commonjs` is not a viable workaround?

**Comment by alexander-akait** [comment]
@DanielRosenwasser Let's wait answers, anyway is it configurable? But yes, I am afraid the same problem will be with any bundler

**Comment by TheLarkInn** [comment]
https://github.com/microsoft/TypeScript/pull/51562 also @DanielRosenwasser you mentioned this is potentially patched already in 5.0?

**Comment by alexander-akait** [comment]
I think we can close because the regression is fixed, the solution is to keep `typescript@4.9.1-beta` until v5 is shipped, unfortunately, we can't do anything from our side. Anyway thank you for a report.

**Comment by jsprw** [comment]
Thank y'all for the thorough investigation.

> I think we can close because the regression is fixed, the solution is to keep `typescript@4.9.1-beta` until v5 is shipped, unfortunately, we can't do anything from our side. Anyway thank you for a report.

> it should be fixed. Can you verify?

I have added a NPM script for Typescript 5 and the emitted code for CommonJS still does not work. Setting module to ESNext works fine indeed for all versions.

Maybe also add a notice to the docs (https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import) that it requires `"module": "ESNext"` for it to work (for now until it's fixed for v5 as well)? I set up the repo with the default settings (`npx tsc --init`) and the config from https://webpack.js.org/guides/getting-started/ so possibly more users will have this issue (like https://github.com/webpack/webpack/discussions/16566). 

> Is there any reason why using `--module esnext` and `--moduleResolution commonjs` is not a viable workaround?

You mean moduleResolution `node`? `commonjs` doesnt seem to be a supported option.

**Comment by jsprw** [comment]
@alexander-akait this is what it emitted for Typescript@5.1.0-dev.20230313:

```typescript
(() => {
  var t = {
      607: function (t, e, n) {
        "use strict";
        var r =
            (this && this.__createBinding) ||
            (Object.create
              ? function (t, e, n, r) {
                  void 0 === r && (r = n);
                  var o = Object.getOwnPropertyDescriptor(e, n);
                  (o &&
                    !("get" in o
                      ? !e.__esModule
                      : o.writable || o.configurable)) ||
                    (o = {
                      enumerable: !0,
                      get: function () {
                        return e[n];
                      },
                    }),
                    Object.defineProperty(t, r, o);
                }
              : function (t, e, n, r) {
                  void 0 === r && (r = n), (t[r] = e[n]);
                }),
          o =
            (this && this.__setModuleDefault) ||
            (Object.create
              ? function (t, e) {
                  Object.defineProperty(t, "default", {
                    enumerable: !0,
                    value: e,
                  });
                }
              : function (t, e) {
                  t.default = e;
                }),
          i =
            (this && this.__importStar) ||
            function (t) {
              if (t && t.__esModule) return t;
              var e = {};
              if (null != t)
                for (var n in t)
                  "default" !== n &&
                    Object.prototype.hasOwnProperty.call(t, n) &&
                    r(e, t, n);
              return o(e, t), e;
            },
          c =
            (this && this.__awaiter) ||
            function (t, e, n, r) {
              return new (n || (n = Promise))(function (o, i) {
                function c(t) {
                  try {
                    u(r.next(t));
                  } catch (t) {
                    i(t);
                  }
                }
                function a(t) {
                  try {
                    u(r.throw(t));
                  } catch (t) {
                    i(t);
                  }
                }
                function u(t) {
                  var e;
                  t.done
                    ? o(t.value)
                    : ((e = t.value),
                      e instanceof n
                        ? e
                        : new n(function (t) {
                            t(e);
                          })).then(c, a);
                }
                u((r = r.apply(t, e || [])).next());
              });
            };
        !(function () {
          c(this, void 0, void 0, function* () {
            const t = yield Promise.all(
              ["import1.ts", "import2.ts", "import3.ts"].map((t) =>
                Promise.resolve(`./dynamic-imports/${t}`).then((t) =>
                  i(n(875)(t))
                )
              )
            );
            console.log(t);
          });
        })();
      },
      875: (t) => {
        function e(t) {
          var e = new Error("Cannot find module '" + t + "'");
          throw ((e.code = "MODULE_NOT_FOUND"), e);
        }
        (e.keys = () => []), (e.resolve = e), (e.id = 875), (t.exports = e);
      },
    },
    e = {};
  function n(r) {
    var o = e[r];
    if (void 0 !== o) return o.exports;
    var i = (e[r] = { exports: {} });
    return t[r].call(i.exports, i, i.exports, n), i.exports;
  }
  (n.o = (t, e) => Object.prototype.hasOwnProperty.call(t, e)), n(607);
})();

```

**Comment by alexander-akait** [comment]
@jsprw We really can't fix it here, code is not statical analizable, we can't analize strings, sorry 

@DanielRosenwasser Friendly ping, maybe you can help here

**Comment by jsprw** [comment]
> @jsprw We really can't fix it here, code is not statical analizable, we can't analize strings, sorry, you can open an issue in typescript repo, I think you are not alone, also this problem happens with any bundler, I am really glad to help your here, but it is out of scope webpack statical analize

Yes, thank you. Added it here to note that it isn't fixed in Typescript v5 either. For now, will await his response before opening an issue there.

**Comment by JodliDev** [comment]
Still occuring on Typescript 5.4.5 :/
Using Typescript 4.9.1-beta still works though.

**Comment by perfmlin** [comment]
webpack.config
output.asyncChunks=false;
