### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by mmurkidjanian** [webpack/webpack#1714]
Hey all, having trouble setting up webpack with my project. I'm getting the error: 
`Uncaught SyntaxError: Unexpected token <`
I'll include a link to the relevant branch on GitHub at the end, but here's a brief description.
The webpack config file is in the root directory. The client folder holds index.html as well as a build folder that holds the bundled js file. The server file holds our server file (using node and express). Ultimately, localhost3000 finds bundle.js, but returns the error I've included above.
Here's a link: https://github.com/mmurkidjanian/plex/tree/test/server/

**Comment by Saturn2888** [comment]
I've gotten the same error, but only when doing a compiled (non-dev) build on Heroku. The way I fixed it was to deploy to Heroku again, and it'd work. Dunno why, but on my local if I do a production compiled build, it now always displays that error. This wasn't happening in the past so something must be triggering it.

What plugins are in your config?

**Comment by pkosenko** [comment]
I am no longer sure whether the problem is webpack or babel-loader.

I am having precisely the same error trying to make webpack 1.12.10 work with babel-loader 6.2.1 to transpile React javascript.   Everywhere I look seems to suggest that new Babel 6 configuration options need to be added to the webpack.config file (because support for react has been dropped from Babel core?), but even when these are added the problem is not solved.  I have an app.js that contains embedded React JSX syntax that babel-loader will simply not recognize.

The compile process works FINE when I run my global Babel 5.8 from the command line: babel app.js -o bundle.js

So Babel 6 no longer WORKS with react?  And hence doesn't work with webpack?

$ webpack
Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.12.10
Time: 328ms
   [0] ./app.js 0 bytes [built] [failed]

ERROR in ./app.js
Module parse failed: c:\software\react\react-test-sites\peter1\app.js Line 70: Unexpected token <
You may need an appropriate loader to handle this file type.
|     // Need to add "className" to the component HTML so that style can be configured.
|     return (
|        <div>
|           <label>Author Last Name: </label>
|           <input type="text" placeholder="Search" onChange={this.handleChange} />

The webpack.config.js file is simplified to 

$ cat webpack.config.js
module.exports = {
    entry: './app.js',
    output: {
        filename: 'bundle.js'
    },
    loaders: [
        {
            test: /\.jsx?$/,  
            exclude: [ /node_modules/ ],
            loader: 'babel-loader',
            query: {
                presets: ['react', 'es2015']   <-- This is SUPPOSED fix the problem but doesn't 
            }
        }
    ]
}

**Comment by s2t2** [comment]
I'm also seeing this on heroku production, but a re-deploy (per @Sawtaytoes) didn't fix the issue. If anyone has solved this, please share.

**Comment by s2t2** [comment]
FYI, after some debugging, I found the issue was due to my express server thinking the contents of the bundle were the contents of the application's index.html page. See a complete solution write-up on [SO](http://stackoverflow.com/questions/35796256/express-webpack-failing-on-dokku-and-heroku/37740210#37740210). Hope this helps someone else in the future.

**Comment by axelerate** [comment]
Hello there. I am having the sam exact issue as @s2t2 .
Only thing is I'm using gunicorn as my web server, not express. Looking at its documentation, I don't think there is any way to prevent it from loading index.html instead of the expected bundled file. Any thoughts?

**Comment by yarondav** [comment]
For what it's worth - I was getting this error when deploying the webpack bundle using nginx static.

I mis configured the path for the app and nginx was configured to send index.html as a fallback. Since the path was misconfigured, there was no real css or js to send so it sent index.html for all requests. Including for 'text/css' and the javascripts which caused this error.

**Comment by peresleguine** [comment]
Probably you have wrong path to your bundles. Express handles all requests sending a file. When it can't find bundle it sends html. So unexpected token is the first symbol of `<html>` tag. Depends on how you inject bundles alter webpack `output.publicPath` for production or edit layout directly.
