### ISSUE TITLE
When can a patch release be published for the default mangle bug fixed last week in master? 5.92.0 and latest 5.92.1 are still broken

### ISSUE THREAD

**Issue by jeffbski-rga** [webpack/webpack#18542]
I got bit by the 5.92.0 default mangle regression which was identified and already fixed a week ago and merged to master. So we just need a release to pick up the change.

- https://github.com/webpack/webpack/issues/18530
- https://github.com/webpack/webpack/pull/18531

As for the nature of the error for anyone reading, you won't get an error at build but at runtime. It will fail to find objects from a default import, they will be undefined.

I am posting this so anyone who hits it will know to downgrade to 5.91.0 until a patch or minor update is published. 

It would be great if a patch release could be created soon to prevent others from hitting this. Thanks!!

**Comment by alexander-akait** [comment]
Yeah, release will be tomorrow, sorry for delay

**Comment by alexander-akait** [comment]
Done - https://github.com/webpack/webpack/releases/tag/v5.93.0

**Comment by jeffbski-rga** [comment]
We were still having the problem with 5.93.0, but 5.94.0 seems to have fixed it. Thanks.
