### ISSUE TITLE
Top level await leaves imported module wrapped in a Promise on HMR

### ISSUE THREAD

**Issue by faergeek** [webpack/webpack#19731]
# Bug report

**What is the current behavior?**

A module with a top-level await is left wrapped in a Promise.

Steps to reproduce:

1. Clone the repo: https://github.com/faergeek/webpack-top-level-await-hmr
2. Install dependencies: `npm install`
3. Start watch mode: `npm start`
4. Edit `src/add.js` file.
5. Observe a console log showing `{ add: undefined, addNs: Promise(...) }`.
6. Comment out line 1 in `src/add.js`, uncomment line 2. This results in an update bubbling up to `src/index.js`, which might be a separate issue as well.
7. Edit `src/add.js` again. This time log shows `{ add: [Function: add], addNs: Object [Module] { .... } }`, which is a normal behavior.

**What is the expected behavior?**

A module should not be left wrapped in a Promise. Parent module should see a result of a Promise resolution instead.

**Other relevant information:**
webpack version: 5.100.2
Node.js version: v24.4.1
Operating System: Arch Linux
Additional tools: webpack-cli

**Comment by faergeek** [comment]
I'll greatly appreciate any advice on where to look in the code to try and contribute a fix for this issue. I'm not familiar with webpack codebase at all.

**Comment by xiaoxiaojx** [comment]
@faergeek Thank you for your feedback. Maybe we need to add "await" here at [2], just like we did at [1], to make the code run properly. https://github.com/webpack/webpack/blob/main/lib/dependencies/HarmonyAcceptDependency.js#L85

<img width="2912" height="1028" alt="Image" src="https://github.com/user-attachments/assets/accba915-3d94-4172-bb44-e5b41ebf2ce7" />

**Comment by faergeek** [comment]
@xiaoxiaojx yes, thank you 👍 Looks like that's what needs to be done. I'm looking into it right now. I guess a piece similar to this https://github.com/webpack/webpack/blob/d5074201cf04423b5ebf2fa8ea1d66c40cf88b11/lib/async-modules/AwaitDependenciesInitFragment.js#L48-L69

needs to be added here https://github.com/webpack/webpack/blob/d5074201cf04423b5ebf2fa8ea1d66c40cf88b11/lib/RuntimeTemplate.js#L885

Or it should be similar to how defer is handled a little bit above it https://github.com/webpack/webpack/blob/d5074201cf04423b5ebf2fa8ea1d66c40cf88b11/lib/RuntimeTemplate.js#L875-L884

I'll experiment with it, but honestly I have no idea how to properly structure the code to open a PR yet.

**Comment by alexander-akait** [comment]
Fixed by https://github.com/webpack/webpack/pull/19741/, @faergeek feel free to feedback

**Comment by faergeek** [comment]
@alexander-akait #19741 doesn't fix this issue itself, it fixes tests not passing on node@10, blocking #19744

**Comment by alexander-akait** [comment]
@faergeek Yeah, my mistake, merged in the wrong order
