### ISSUE TITLE
webpack -p does not set NODE_ENV to "production" webpack@2.0.7-beta

### ISSUE THREAD

**Issue by MystK** [webpack/webpack#2065]
I am on windows 10. Can anyone else reproduce this?

**Comment by TheLarkInn** [comment]
Can you show an example of this, or how you verified it wasn't setting correctly? I wanted to try and tackle this one.

**Comment by sokra** [comment]
was fixed, as far as I know.

**Comment by deanshub** [comment]
still happens to me, also on windows 10,
running:
```
webpack -p --progress --colors
```
or 
```
webpack -p --env=prod --progress --colors
```

inside webpack.config.js
```
console.log(process.env.NODE_ENV); // prints undefined
```
