### ISSUE TITLE
On b23's configuration validation

### ISSUE THREAD

**Issue by phaistonian** [webpack/webpack#3022]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.23

**Please tell us about your environment:**
OSX

**Current behavior:**

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry['something'] should be one of these:
   string | [string]
   The entry point for one output file
```

**Expected/desired behavior:**
Should work since I am actually passing an array of strings as entry point(s)

**Comment by sokra** [comment]
could you include your entry configuration?

**Comment by phaistonian** [comment]
@sokra 

```
module.exports = {
  index: ['./js/index.js', './css/index.styl'],
  redirect: ['./redirect/redirect.js', './redirect.styl'],
};
```

**Comment by sokra** [comment]
doesn't look that wrong...

**Comment by sokra** [comment]
@gajus

**Comment by gajus** [comment]
Fixed in https://github.com/webpack/webpack/pull/3024

**Comment by phaistonian** [comment]
@gajus Great work, you all.

Hopefully the new release won't take long to ship.

Thank you.

**Comment by phaistonian** [comment]
FYI,

@gajus, @sokra:  Updated to b25 and the issue is still there.

**Comment by sokra** [comment]
@gajus could you take another look?

**Comment by SpaceK33z** [comment]
I'm on b25 too but it seems to work. Tested with this entry config:

```js
entry: {
	index: ["./app.js", "./bar.js"],
	other: ["./app.js", "./bar.js"],
},
```

@phaistonian, can you share what your `entry` config looks like?

**Comment by phaistonian** [comment]
@SpaceK33z of course.

Here it is:

```js
module.exports = {
  bestprice: ['./js/index.js', './css/index.styl'],
  mediakit: ['./pages/mediakit/mediakit.js', './css/index.styl'],
  about: ['./pages/about/about.js', './pages/about/about.styl', './css/index.styl'],
  redirect: ['./pages/item/redirect/redirect.js', './pages/item/redirect/redirect.styl'],
};
```

Perhaps, the issue is that I am importing the entry - as opposed to declaring directly into config.

**Comment by SpaceK33z** [comment]
@phaistonian interesting, that looks like the same structure as my config. How do you add that module to your `entry` config?

**Comment by phaistonian** [comment]
There :)

![image](https://cloud.githubusercontent.com/assets/796530/19184182/96b5ff1a-8c84-11e6-94b2-cd0fc2c7cd7a.png)

**Comment by SpaceK33z** [comment]
@phaistonian, hm even that seems to work for me. Just debugging here, but are you sure you have b25? If you look in `node_modules/webpack/package.json`, in the `_id` property, you can see what version is actually installed.

**Comment by phaistonian** [comment]
I am not on b25 since I can't go there because of this issue.

Downgraded to b22.

**Comment by SpaceK33z** [comment]
Yeah okay, but did you check if you were actually on b25? Sorry for doubting you, but npm can sometimes ignores the new version if you do a `npm install`. Only asking this because I seem to have the exact same config structure and it works, sorry.

**Comment by phaistonian** [comment]
@SpaceK33z More than once, but let me do it again :)

Bundling ...

**Comment by phaistonian** [comment]
Here

![image](https://cloud.githubusercontent.com/assets/796530/19184722/1d4c415e-8c87-11e6-8b0a-7d2bfe0a2a21.png)

**Comment by SpaceK33z** [comment]
Very weird. I even copied your config for `entry` (it doesn't matter that the files don't actually exist on my disk, it will validate before that) and it still works.

You did check `node_modules/webpack/package.json` and verified it had `"_id": "webpack@2.1.0-beta.25"`, right?

**Comment by phaistonian** [comment]
I am on b25.

![image](https://cloud.githubusercontent.com/assets/796530/19184958/34ff5538-8c88-11e6-9191-1d20ccc855fb.png)

**Comment by phaistonian** [comment]
I think I got it .

(wtf, btw)

**Comment by phaistonian** [comment]
yes.

```js
const newEntry = {};
Object.keys(entry).forEach(key => {
  newEntry[key] = entry[key];
});
```

and using the newEntry did the trick.

This is (far) beyond me.

**Comment by phaistonian** [comment]
The only theory I have is that `entry` is reference and somehow it's mutated when Webpack does the bundling.

Thing is, using `entry: Object.assign({}, entry)` did not the trick as expected.

Fun times.

**Comment by jonrimmer** [comment]
I was getting the same error. The problem turned out to be a duplicate entry in one of my arrays. I was only able to figure it out by adding some logging to ```WebpackOptionsValidationError.formatValidationError``` to log the underlying error object.

It seems like  the problem is webpack reports the top-level error from the schema validation, but not child errors which include the specific details of what went wrong.

**Comment by phaistonian** [comment]
@jonrimmer Could you point a how-to on the logging part?

**Comment by jonrimmer** [comment]
@phaistonian I edited ```node_modules/webpack/lib/WedpackOptionsValidationError.js``` and added ```console.dir(err)``` at line 24 (which should be the beginning of the ```formatValidationError``` function declaration).

It logs a pretty complicated object, but I noticed it has a ```children``` array property that contain what look like sub-errors from the validator.

**Comment by gajus** [comment]
@phaistonian Do you still have the issue?

**Comment by phaistonian** [comment]
Using https://github.com/webpack/webpack/issues/3022#issuecomment-252192793 no.

Not using it, yes.

**Comment by gajus** [comment]
@phaistonian could you create a repository with enough code to replicate the issue?

**Comment by phaistonian** [comment]
A bit busy at the moment ;(

It's nothing much - really.

All I do is `require` this (https://github.com/webpack/webpack/issues/3022#issuecomment-252185536) and use it as entry.

Nothing fancier than that.

**Comment by gajus** [comment]
> All I do is require this (#3022 (comment)) and use it as entry.

I have tried it and it works. There is something different about your setup. If you could make a repository (and include `node_modules/`), that would be insanely useful, as opposed to trying to guess whats different about your setup.

**Comment by SpaceK33z** [comment]
I'm closing this since @gajus also confirmed it's working (I did too) and there seems to be some other issue. Feel free to re-open if you can provide more information.

**Comment by SpaceK33z** [comment]
I'm closing this since @gajus also confirmed it's working (I did too) and there seems to be some other issue. Feel free to re-open if you can provide more information.

**Comment by SpaceK33z** [comment]
I'm closing this since @gajus also confirmed it's working (I did too) and there seems to be some other issue. Feel free to re-open if you can provide more information.

**Comment by Sawtaytoes** [comment]
In `WebpackOptionsValidationError.js`, doing `console.dir(err.children)` narrowed down the errors I was having on Webpack 2 newer than b22. I'm currently on `2.20-rc.1`.

In my setup, it revealed some issues where props were on the Webpack object such as colors and minimize which are no longer accepted. I don't know what would replace these, but those, plus a custom stylus declaration were causing the bulk of the issues.

I still wasn't able to build, but I think my issue is slightly different because my error only says:
```
D:\Projects\Personal\Ghadyani-Framework-Webpack-React-Redux\node_modules\webpack\lib\webpack.js:17
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
```

On the other hand, it's definitely erroring without any given reason. I'm also loading Webpack through a JS file:
```js
new WebpackDevServer(webpack(webpackClientConfig), webpackServerConfig)
.listen(config.getPort(), config.getHostname(), onBuild.bind(null, 'webpack-dev-server', config.getServerUrl))
```

It's erroring for me on `webpack(webpackClientConfig)` if it helps.

**Comment by Sawtaytoes** [comment]
Some more work into this, these are the config props that caused errors. I do not know if there's any equivalent in Webpack 2 yet.

**Webpack config**
```
colors
debug
minimize
prerender
```

**Webpack-Dev-Server config**
```
cert
key
progress
```

And then I'm having a completely different issue after finally getting it to build where it can't seem to load modules using the `import` syntax when I do this in my `.babelrc`:
```
{
  "plugins": [
    "transform-runtime",
  ],
  "presets": [
    // "latest",
    ["latest", {
      "es2015": { "modules": false }
    }],
    "stage-0",
    "react",
  ]
}
```

It works now otherwise, but commenting out those configs isn't necessarily the solution I was looking for either.

**Comment by SpaceK33z** [comment]
@Sawtaytoes, for `cert` and `key` you could use `config.isSecure() ? ... : null` instead, that should work. As for `progress` option, that's currently only possible via commandline with `--progress`.

**Comment by Sawtaytoes** [comment]
Thanks! I switched it to `null` for missing certs.

It seems Webpack's `ProgressPlugin` covers progress when building through Node.js.

Doing some more testing for production builds, seems there are some more changes in Webpack 2's config. I don't see many (if any) articles or YouTube vids on conversions so it's a wild frontier right now :/.

I love the new docs on webpack.js.org, but some required changes didn't show up in the migration guide.

**Comment by SpaceK33z** [comment]
@Sawtaytoes, if we missed anything in the migration docs (https://webpack.js.org/guides/migrating), we would really appreciate it if you could send a PR to add it!

**Comment by Sawtaytoes** [comment]
I created a pull request: https://github.com/Sawtaytoes/webpack.js.org/pull/1
I noted the information that I used to help me convert my files over.
