### ISSUE TITLE
[ES2015] Import module used before it's declaration

### ISSUE THREAD

**Issue by aitboudad** [webpack/webpack#3972]
https://github.com/ui-router/ng2/blob/master/src/ng2.ts#L2
![selection_054](https://cloud.githubusercontent.com/assets/1753742/21965239/ca59ea0c-db53-11e6-851c-bfcd74597082.png)

**Comment by TheLarkInn** [comment]
Is it possible to show what the transpiled version of that file looks like before it is bundled?

**Comment by aitboudad** [comment]
https://github.com/ui-router/ng2/blob/master/src/ng2.ts#L2

**Comment by aitboudad** [comment]
it was working before, I solved this by importing the lib before `export`

Before:
```ts
export * from "ui-router-core";
```

After
```ts
import "ui-router-core";
export * from "ui-router-core";
```

**Comment by TheLarkInn** [comment]
@aitboudad Was there a reason for using `export * from "ui-router-core"`?

**Comment by TheLarkInn** [comment]
Oh I apologize I understand now. This is what the lib is doing. Can this module be used without angular and non-ts app? I want to eliminate typescript to debug this.

**Comment by aitboudad** [comment]
I think so

**Comment by TheLarkInn** [comment]
Would you mind creating a small example repo? I'm going to try a few things myself as well.

**Comment by aitboudad** [comment]
see https://github.com/aitboudad/angular2-aot-webpack

```
git clone https://github.com/aitboudad/angular2-aot-webpack
cd angular2-aot-webpack
yarn install
yarn start
http://localhost:9000/
```

**Comment by TheLarkInn** [comment]
So it's really hard to verify if there is an issue since TS is responsible for the transpilation. (Thus why I'm looking for an issue reproducible in JS first). 

So far I've tested the following. 

**index.js (entry property)**
```js
import {getStuff, number, fromExport} from './export';

console.log(getStuff());
```

**export.js**
```js
export * from "./vendor"; 

const fromExport = "FROM EXPORT";
export {fromExport}
```


**vendor.js**
```js
const foo = "FROM VENDOR";
const getStuff = () => {
    return {some: "FROM VENDOR"};
}

export const number = 43;
export {getStuff, foo};
```

My resulting bundle looks as the following: 

**bundle.js (runtime omitted)**
```js
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__vendor__ = __webpack_require__(1);
/* harmony namespace reexport (by used) */ __webpack_require__.d(__webpack_exports__, "a", function() { return __WEBPACK_IMPORTED_MODULE_0__vendor__["a"]; });
/* unused harmony export fromExport */
 //EXPORT ALL EXPORTS FROM VENDOR

const fromExport = "FROM EXPORT";


/***/ }),
/* 1 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return getStuff; });
/* unused harmony export foo */
const foo = "FROM VENDOR";
const getStuff = () => {
    return {some: "FROM VENDOR"};
}

const number = 43;
/* unused harmony export number */



/***/ }),
/* 2 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__export__ = __webpack_require__(0);


console.log(__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__export__["a" /* getStuff */])());


/***/ })
/******/ ]);
```

So far it appears in this case that the ordering is correct when just ES2015. (Thus my concern).

**Comment by sokra** [comment]
Could you test it against the lastest (rc.6) version? Should be fixed... (I hope at least)

**Comment by aitboudad** [comment]
Still persist on my side, if I downgrade to webpack `2.1.0-beta.27` It works again
I think that since https://github.com/webpack/webpack/pull/3419

**Comment by sokra** [comment]
Ok I think I found the issue. PR incoming...

**Comment by TheLarkInn** [comment]
I have confirmed this fixes the issue locally.

@aitboudad we just released RC7. Would you mind verifying this fixes the problem for you?

**Comment by aitboudad** [comment]
That's works for me too, many thanks!

**Comment by TheLarkInn** [comment]
Thank you for reporting this!!!

**Comment by sokra** [comment]
🎉 😄
