### ISSUE TITLE
Wrong Arguments for style-loader when loading from browser

### ISSUE THREAD

**Issue by mengxingshike2012** [webpack/webpack#4040]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I use webpack 2.2 to build my project, while build is successed but the browser failed to load the output js file.
The output file has SyntaxError. See the first param of module.hot.accept
````
  // Hot Module Replacement
if(true) {
	// When the styles change, update the <style> tags
	if(!content.locals) {
		module.hot.accept("./node_modules/css-loader/index.js!./node_modules/antd/lib/affix/style/index.css""./node_modules/css-loader/index.js!./node_modules/antd/lib/affix/style/index.css", function() {
			var newContent = __webpack_require__("./node_modules/css-loader/index.js!./node_modules/antd/lib/affix/style/index.css");
			if(typeof newContent === 'string') newContent = [[module.i, newContent, '']];
			update(newContent);
		});
	}
	// When the module is disposed, remove the <style> tags
	module.hot.dispose(function() { update(); });
}
````
**If the current behavior is a bug, please provide the steps to reproduce.**
 Please help to advise if there is something wrong with my configurations.
````
module.exports = {
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, 'src/index.html'),
    }),
    // faster code reload on changes
    new webpack.HotModuleReplacementPlugin(),
    // prints more readable module names in the browser console on HMR updates
    new webpack.NamedModulesPlugin(),
    new webpack.LoaderOptionsPlugin({
      options: {  
        sassLoader: {
          includePaths: [path.resolve(__dirname, "src/styles")],
        }
      }
    })
  ],
  resolve: {
    modules: [
      path.resolve(__dirname, 'src'),
      'node_modules',
    ],
    extensions: ['.js', '.jsx', '.css'],
  },
  devtool: 'source-map',
  cache: false,
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader',
        ]
      },
      {
        test: /\.scss$/,
        use: [
            'style-loader',
            'css-loader?modules&' +
            'importLoaders=1&' +
            'localIdentName=[name]__[local]___[hash:base64:5]',
            'sass-loader',
        ],
      },
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        use: ['babel-loader'],
      },
      {
        test: /\.svg$/,
        use: 'url-loader?limit=65000&mimetype=image/svg+xml&name=public/fonts/[name].[ext]',
      },
      {
        test: /\.woff$/,
        use: 'url-loader?limit=65000&mimetype=application/font-woff&name=public/fonts/[name].[ext]',
      },
      {
        test: /\.woff2$/,
        use: 'url-loader?limit=65000&mimetype=application/font-woff2&name=public/fonts/[name].[ext]',
      },
      {
        test: /\.[ot]tf$/,
        use: 'url-loader?limit=65000&mimetype=application/octet-stream&name=public/fonts/[name].[ext]',
      },
      {
        test: /\.eot$/,
        use: 'url-loader?limit=65000&mimetype=application/vnd.ms-fontobject&name=public/fonts/[name].[ext]',
      },
    ],
  },
  entry: [
    'babel-polyfill',
    'react-hot-loader/patch',
    `webpack-dev-server/client?http://${HOST}:${PORT}`,
    'webpack/hot/only-dev-server',
    path.resolve(__dirname, 'src/index.jsx'),
  ],
  devServer: {
    contentBase: './www',
    quiet: false,
    historyApiFallback: true,
    hot: true,
    port: PORT,
    host: HOST,
    noInfo: false,
    publicPath: '/www/',
    headers: {
        'Access-Control-Allow-Origin': '*',
    },
    proxy: {
      '/': {
        target: REMOTE,
        secure: false,
        bypass(req) {
          console.log(req.path);
          if (req.path === '/') {
            return '/www/index.html';
          } else if (req.path.substr(0, 4) === '/www') {
            return true;
          }
        }
      },
    },
  },
  output: {
    path: path.resolve(__dirname, 'www'),
    publicPath: '/www/',
    filename: 'app.js',
  },
};
````

**What is the expected behavior?**
Works ok with webpack2.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
We use antd together with Webpack,  and I have changed the antd-import setting as it is reffered  [ant-design/babel-plugin-import](https://github.com/ant-design/babel-plugin-import/issues/54);
The error code located in the style-loader, I tried to see the value when run webpack cli and it seems to be okey
````
"antd": "^1.11.1",
 "react-hot-loader": "^3.0.0-beta.6",
 "style-loader": "^0.13.1",
 "webpack": "^2.2.0",
 "webpack-dev-server": "^2.2.0"
````

**Comment by BartJanvanAssen** [comment]
Same over here! have not found any solutions yet...

**Comment by BartJanvanAssen** [comment]
https://github.com/webpack-contrib/style-loader/issues/18
fixed my issue

**Comment by mengxingshike2012** [comment]
@BartJanvanAssen you mean remove the hot: true in the config of webpackDevServer ? I've tried but it not worke for me. And [the official example](https://webpack.js.org/guides/hmr-react/) of webpack2 also has both the plugin and this devServer configuration.Strange.

**Comment by e110c0** [comment]
I ran into the same issue, removing hot:true from the config didnt solve the issue. Removing it from the command line and keeping it in the config worked though.

since the official example only uses "webpack-dev-server" to start the dev server, the example itself is fine. Most other resources on the internet are using either the --hot command line option exclusively or in combination with the config option.

**Comment by gdaolewe** [comment]
The same happens for me if and only if I use `NamedModulePlugin`. Try removing that, it's only a mild quality of life improvement.

**Comment by timse** [comment]
is this a webpack dev server or a webpack issue?
