### ISSUE TITLE
cannot mute webpack/hot/dev-server console.logs

### ISSUE THREAD

**Issue by tsm91** [webpack/webpack#4115]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
Right now [webpack/hot/dev-server/](https://github.com/webpack/webpack/blob/master/hot/dev-server.js) spams my console, especially with multiple hot entry points (double spam).

```
[HMR] Waiting for update signal from WDS...
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ../ng-cli/node_modules/css-loader/index.js!../ng-cli/node_modules/sass-loader/index.js!./src/assets/styles/main.scss
[HMR] App is up to date.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Use HMR in one of the entry points and check browser console.

**What is the expected behavior?**
Selective console logs in browser. Values: `none`, `error`, `warning`, `info`. 

Webpack-dev-server has a [devServer.clientLogLevel](https://webpack.js.org/configuration/dev-server/#devserver-clientloglevel) option, [implemented here](https://github.com/webpack/webpack-dev-server/pull/579). The problem is, `webpack/hot/dev-server` should respect this option.

Files doing the spam:
  * https://github.com/webpack/webpack/blob/master/hot/dev-server.js
  * https://github.com/webpack/webpack/blob/master/hot/log-apply-result.js

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

win10/ubuntu 1604, node v7.4.0, npm v4.0.5, webpack-, webpack-dev-server v2.2.0

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by tsm91** [comment]
@sokra boo, im afraid i dont have th power to reopen the issue

updated the issue based on the template

for ppl who dont wanna wait just copy those 2 files, comment out the relevant console.logs and reference ur own `dev-server.js`, thats it

**Comment by shubheksha** [comment]
I'd like to work on this!

**Comment by tsm91** [comment]
+1 will do a code review

**Comment by LucianoGraziani** [comment]
What is the different between the HotModuleReplacementPlugin and the devServer.hot flag?

**Comment by tsm91** [comment]
@LucianoGraziani https://github.com/webpack/webpack-dev-server/issues/97#issuecomment-69726201

**Comment by LucianoGraziani** [comment]
Thank you @tsm91! I never really understood HRM hah. I thought that just adding the plugin will work 🙈

**Comment by mjanssen** [comment]
Hey guys, is this 'issue' already resolved or is there already a way to allow certain log messages (like "updated modules") but disable the "Checking for updates on the server" message?

My console is flooding with [HMR] logs 😥  (see attached image).
![image](https://cloud.githubusercontent.com/assets/1145427/24860318/4fb9aac4-1df4-11e7-9eb7-bb615260dd5c.png)

**Comment by kazazor** [comment]
Another hacky temp solution for now in case you do not want to copy the needed files and reference them instead of webpack's files:

```js
////////// Temp solution ///////////

// TODO - Disable all info / logs for HMR until the log level issue will be fixed - https://github.com/webpack/webpack/issues/4115
const replaceInFile = (filePath, searchRegex, replaceString) => {
  const fs = require('fs');
  filePath = path.resolve(filePath);

  fs.readFile(filePath, 'utf8', function (err,data) {
    if (err) {
      return console.log(err);
    }

    const result = data.replace(searchRegex, replaceString);

    fs.writeFile(filePath, result, 'utf8', function (err) {
      if (err) {
        return console.log(err);
      }
    });
  });
};

const consoleRegex = /(console\.(info|log).+\);)/g;

// Why do we add `;\n{}`? Some part of the code has if conditions without {} around their content.
// So we'll just comment out the console.log line we'll get an error. This way we're adding a line that doesn't do anything.
const emptyStatement = '//$1;\n{}';
replaceInFile("node_modules/webpack/hot/dev-server.js", consoleRegex, emptyStatement);
replaceInFile("node_modules/webpack/hot/log-apply-result.js", consoleRegex, emptyStatement);

////////// End of temp solution ///////////
```

The above comments out all the `console.log` / `console.info` (just change the regex as you wish) in the original webpack's HMR files.

**Comment by esbenp** [comment]
This issue is fixed by https://github.com/webpack/webpack/pull/4960 and https://github.com/webpack/webpack-dev-server/pull/926 , right? @sokra @TheLarkInn

**Comment by psimyn** [comment]
@esbenp fixed for some messages. Still getting `[HMR] Waiting for update signal from WDS...`

**Comment by drewlustro** [comment]
Would love this to get fixed. +1

**Comment by IAMtheIAM** [comment]
Hey guys, none of these suggestions worked for me, except the CLI option does!!

``` 
webpack --client-log-level warning
// or 
webpack --client-log-level error
```

It defaults to `info` which is where all the [HMR] and [WDS] spam comes from.

**Comment by evilebottnawi** [comment]
Maybe better fix this problem in `webpack-dev-server`/`webpack-dev-middleware`

**Comment by noelebrun** [comment]
Hey guys,

@evilebottnawi Seems like this config is already handled in webpack-dev-server (https://github.com/webpack/webpack-dev-server/blob/34a4a26ccd8ea9f0349a9d3b257f686d43f027f8/client-src/default/index.js#L101).

What do you think about adding an optional query string parameter to define the log level? This parameter would override the logLevel set by webpack-dev-server if defined. (Even tho this case should not really happen since webpack-dev-server is adding the hot dev server without any parameters).

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack/webpack-dev-server

**Comment by agrublev** [comment]
```devServer: {
        clientLogLevel: "silent",```

**Comment by MaxmaxmaximusGitHub** [comment]
@agrublev this not working

**Comment by peterpoe** [comment]
Anyone using gatsby, you can alter webpack-hot-middleware configuration by adding the following to gatsby-node.js:

```js
exports.onCreateWebpackConfig = ({ actions, stage, getConfig }) => {
  if (stage === 'develop') {
    // First commons entry is webpack-hot-middleware
    // @see https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js
    const commons = getConfig().entry.commons
    commons[0] += '&noInfo=true'
    actions.setWebpackConfig({
      entry: {
        commons,
      },
    })
  }
}
```
