### ISSUE TITLE
Entry module not found: Error: Can't resolve 'html-webpack-plugin/lib/loader.j s'

### ISSUE THREAD

**Issue by JanStureNielsen** [webpack/webpack#4122]
**Do you want to request a *feature* or report a *bug*?**

**Bug**

I upgraded from `angular-cli@1.0.0-beta.21` to `angular-cli@1.0.0-beta.25.5`, making all necessary changes to get my app running with `ng serve` successfully. However, when I attempt to deploy to Heroku, it fails with the curious error below.

My [SO question is unanswered as of this](http://stackoverflow.com/questions/41877754/entry-module-not-found-error-cant-resolve-html-webpack-plugin-lib-loader-j-s). It's not clear to me where this issue is best asked but I've raised with [Angular CLI (no reply as of this)](https://github.com/angular/angular-cli/issues/4237), seems like `webpack` is next in line, then `html-webpack-plugin` or perhaps the `@ngtools` and/or `style-loader`. Perhaps someone with more knowledge of WebPack could point the direction?

**What is the current behavior?**
An `ng build --prod` of my (unfortunately private) project fails on Heroku but works fine on my local Linux setup.

    remote:        ERROR in   Error: Child compilation failed:
    remote:        Entry module not found: Error: Can't resolve 'html-webpack-plugin/lib/loader.j  s' in '/tmp/build_7c419ad06257b748ec6f7c819360bd4b':
    remote:        Error: Can't resolve 'html-webpack-plugin/lib/loader.js' in '/tmp/build_7c419a  d06257b748ec6f7c819360bd4b'
    remote:        
    remote:        - compiler.js:76
    remote:        [lib]/[angular-cli]/[html-webpack-plugin]/lib/compiler.js:76:16
    remote:        
    remote:        - Compiler.js:280 Compiler.<anonymous>
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compiler.js:280:10
    remote:        
    remote:        - Compiler.js:480
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compiler.js:480:13
    remote:        
    remote:        - Tapable.js:138 next
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:138:11
    remote:        
    remote:        - CachePlugin.js:62 Compiler.<anonymous>
    remote:        [lib]/[angular-cli]/[webpack]/lib/CachePlugin.js:62:5
    remote:        
    remote:        - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:142:13
    remote:        
    remote:        - Compiler.js:477
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compiler.js:477:10
    remote:        
    remote:        - Tapable.js:138 next
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:138:11
    remote:        
    remote:        - suppress-entry-chunks-webpack-plugin.js:38 Compilation.<anonymous>
    remote:        [lib]/[angular-cli]/plugins/suppress-entry-chunks-webpack-plugin.js:38:17
    remote:        
    remote:        - Tapable.js:142 Compilation.applyPluginsAsyncSeries
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:142:13
    remote:        
    remote:        - Compilation.js:615 self.applyPluginsAsync.err
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compilation.js:615:19
    remote:        
    remote:        - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:131:46
    remote:        
    remote:        - Compilation.js:606 self.applyPluginsAsync.err
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compilation.js:606:11
    remote:        
    remote:        - Tapable.js:138 next
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:138:11
    remote:        
    remote:        - UglifyJsPlugin.js:140 Compilation.compilation.plugin
    remote:        [lib]/[angular-cli]/[webpack]/lib/optimize/UglifyJsPlugin.js:140:5
    remote:        
    remote:        - Tapable.js:142 Compilation.applyPluginsAsyncSeries
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:142:13
    remote:        
    remote:        - Compilation.js:601 self.applyPluginsAsync.err
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compilation.js:601:10
    remote:        
    remote:        - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:131:46
    remote:        
    remote:        - Compilation.js:597 sealPart2
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compilation.js:597:9
    remote:        
    remote:        - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:131:46
    remote:        
    remote:        - Compilation.js:545 Compilation.seal
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compilation.js:545:8
    remote:        
    remote:        - Compiler.js:474
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compiler.js:474:16
    remote:        
    remote:        - Tapable.js:225
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:225:11
    remote:        
    remote:        - Compilation.js:452 _addModuleChain
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compilation.js:452:11
    remote:        
    remote:        - Compilation.js:345 Compilation.errorAndCallback
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compilation.js:345:4
    remote:        
    remote:        - Compilation.js:362 moduleFactory.create
    remote:        [lib]/[angular-cli]/[webpack]/lib/Compilation.js:362:12
    remote:        
    remote:        - NormalModuleFactory.js:234
    remote:        [lib]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:234:19
    remote:        
    remote:        - NormalModuleFactory.js:59 onDoneResolving
    remote:        [lib]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:59:20
    remote:        
    remote:        - NormalModuleFactory.js:126
    remote:        [lib]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:126:20
    remote:        
    remote:        - async.js:3694
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:3694:9
    remote:        
    remote:        - async.js:356
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:356:16
    remote:        
    remote:        - async.js:934 iteratorCallback
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:934:13
    remote:        
    remote:        - async.js:840
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:840:16
    remote:        
    remote:        - async.js:3691
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:3691:13
    remote:        
    remote:        - async.js:21 apply
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:21:25
    remote:        
    remote:        - async.js:56
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:56:12
    remote:        
    remote:        - async.js:1013
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:1013:9
    remote:        
    remote:        - async.js:356
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:356:16
    remote:        
    remote:        - async.js:934 iteratorCallback
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:934:13
    remote:        
    remote:        - async.js:840
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:840:16
    remote:        
    remote:        - async.js:1010
    remote:        [lib]/[angular-cli]/[async]/dist/async.js:1010:13
    remote:        
    remote:        - NormalModuleFactory.js:262
    remote:        [lib]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:262:19
    remote:        
    remote:        - Resolver.js:70 onResolved
    remote:        [lib]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:70:11
    remote:        
    remote:        - createInnerCallback.js:31 loggingCallbackWrapper
    remote:        [lib]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:    31:19
    remote:        
    remote:        - Resolver.js:138 afterInnerCallback
    remote:        [lib]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:138:10
    remote:        
    remote:        - createInnerCallback.js:31 loggingCallbackWrapper
    remote:        [lib]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:    31:19
    remote:        
    remote:        - Tapable.js:181 Resolver.applyPluginsAsyncSeriesBailResult1
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:181:46
    remote:        
    remote:        - Resolver.js:125 innerCallback
    remote:        [lib]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/Resolver.js:125:19
    remote:        
    remote:        - createInnerCallback.js:31 loggingCallbackWrapper
    remote:        [lib]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/createInnerCallback.js:    31:19
    remote:        
    remote:        - Tapable.js:283
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:283:15
    remote:        
    remote:        - UnsafeCachePlugin.js:39
    remote:        [lib]/[angular-cli]/[webpack]/[enhanced-resolve]/lib/UnsafeCachePlugin.js:39    :4
    remote:        
    remote:        
    remote:        
    remote:        ERROR in multi ./src/main.ts
    remote:        Module not found: Error: Can't resolve '@ngtools/webpack' in '/tmp/build_7c419ad06257b748ec6f7c819360bd4b'
    remote:        @ multi ./src/main.ts
    remote:        
    remote:        ERROR in multi ./src/app/assets/css/main.scss
    remote:        Module not found: Error: Can't resolve 'style-loader' in '/tmp/build_7c419ad06257b748ec6f7c819360bd4b'
    remote:        @ multi ./src/app/assets/css/main.scss
    remote:        
    remote:        ERROR in   TypeError: Cannot read property 'match' of undefined
    remote:        
    remote:        - suppress-entry-chunks-webpack-plugin.js:44 filterFn
    remote:        [lib]/[angular-cli]/plugins/suppress-entry-chunks-webpack-plugin.js:44:76
    remote:        
    remote:        - Array.filter
    remote:        
    remote:        - suppress-entry-chunks-webpack-plugin.js:47 Compilation.<anonymous>
    remote:        [lib]/[angular-cli]/plugins/suppress-entry-chunks-webpack-plugin.js:47:59
    remote:        
    remote:        - Tapable.js:208 Compilation.applyPluginsAsyncWaterfall
    remote:        [lib]/[angular-cli]/[tapable]/lib/Tapable.js:208:13
    remote:        
    remote:        - util.js:16 Compilation.tryCatcher
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/util.js:16:23
    remote:        
    remote:        
    remote:        - index.js:636
    remote:        [lib]/[angular-cli]/[html-webpack-plugin]/index.js:636:12
    remote:        
    remote:        - index.js:152
    remote:        [lib]/[angular-cli]/[html-webpack-plugin]/index.js:152:16
    remote:        
    remote:        - util.js:16 tryCatcher
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/util.js:16:23
    remote:        
    remote:        - promise.js:510 Promise._settlePromiseFromHandler
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/promise.js:510:31
    remote:        
    remote:        - promise.js:567 Promise._settlePromise
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/promise.js:567:18
    remote:        
    remote:        - promise.js:612 Promise._settlePromise0
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/promise.js:612:10
    remote:        
    remote:        - promise.js:691 Promise._settlePromises
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/promise.js:691:18
    remote:        
    remote:        - async.js:133 Async._drainQueue
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/async.js:133:16
    remote:        
    remote:        - async.js:143 Async._drainQueues
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/async.js:143:10
    remote:        
    remote:        - async.js:17 Immediate.Async.drainQueues
    remote:        [lib]/[angular-cli]/[bluebird]/js/release/async.js:17:14
    remote:        
    remote:        
    remote:        
    remote:        npm ERR! Linux 3.13.0-105-generic
    remote:        npm ERR! argv "/tmp/build_7c419ad06257b748ec6f7c819360bd4b/.heroku/node/bin/node" "/tmp/build_7c419ad06257b748ec6f7c819360bd4b/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_7c419ad06257b748ec6f7c819360bd4b/.npmrc"
    remote:        npm ERR! node v6.9.4
    remote:        npm ERR! npm  v3.10.10
    remote:        npm ERR! code ELIFECYCLE
    remote:        npm ERR! fm-ui@2.0.0-alpha.15 postinstall: `ng build --prod`
    remote:        npm ERR! Exit status 1
    remote:        npm ERR!
    remote:        npm ERR! Failed at the fm-ui@2.0.0-alpha.15 postinstall script 'ng build --prod'.
    remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
    remote:        npm ERR! If you do, this is most likely a problem with the fm-ui package,
    remote:        npm ERR! not with npm itself.
    remote:        npm ERR! Tell the author that this fails on your system:
    remote:        npm ERR!     ng build --prod
    remote:        npm ERR! You can get information on how to open an issue for this project with:
    remote:        npm ERR!     npm bugs fm-ui
    remote:        npm ERR! Or if that isn't available, you can get their info via:
    remote:        npm ERR!     npm owner ls fm-ui
    remote:        npm ERR! There is likely additional logging output above.
    remote:        
    remote:        npm ERR! Please include the following file with any support request:
    remote:        npm ERR!     /tmp/build_7c419ad06257b748ec6f7c819360bd4b/npm-debug.log
    remote: 
    remote: -----> Build failed
    remote:        
    remote:        We're sorry this build is failing! You can troubleshoot common issues here:
    remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
    remote:        
    remote:        If you're stuck, please submit a ticket so we can help:
    remote:        https://help.heroku.com/
    remote:        
    remote:        Love,
    remote:        Heroku
    remote:        
    remote:  !     Push rejected, failed to compile Node.js app.
    remote: 
    remote:  !     Push failed

**If the current behavior is a bug, please provide the steps to reproduce.**

Sadly, I have not, yet, been able to create a reproduction.

**What is the expected behavior?**

A successful build just like the local build.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

`Linux 3.13.0-105-generic`
```
angular-cli: 1.0.0-beta.26
node: 6.9.4
os: linux x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/material: 2.0.0-beta.1
@angular/compiler-cli: 2.4.5
webpack: 2.2.0
html-webpack-plugin: 2.26.0
```

**Comment by bebraw** [comment]
Can you check which version of html-webpack-plugin its using? I have a feeling this might have been fixed there already.

**Comment by JanStureNielsen** [comment]
@bebraw -- `html-webpack-plugin@^2.19.0`. I'll add this to the description as well.

**Comment by JanStureNielsen** [comment]
@bebraw -- I've corrected the `webpack` version to `2.2.0` -- sorry about the initial reporting error.

**Comment by vanbrigoli** [comment]
Same error in deploying nodejs app in heroku using angular-cli.

**Comment by SpaceK33z** [comment]
This is an issue in html-webpack-plugin, see https://github.com/ampedandwired/html-webpack-plugin/pull/555 for more info.

**Comment by SpaceK33z** [comment]
`html-webpack-plugin@2.28.0` was just released, that should fix the issue.

**Comment by JanStureNielsen** [comment]
@SpaceK33z -- yes, `html-webpack-plugin@2.28.0` addresses the first error; but the other errors remain:
```
remote:        ERROR in multi ./src/main.ts
remote:        Module not found: Error: Can't resolve '@ngtools/webpack' in '/tmp/build_7c419ad06257b748ec6f7c819360bd4b'
remote:        @ multi ./src/main.ts
remote:        
remote:        ERROR in multi ./src/app/assets/css/main.scss
remote:        Module not found: Error: Can't resolve 'style-loader' in '/tmp/build_7c419ad06257b748ec6f7c819360bd4b'
remote:        @ multi ./src/app/assets/css/main.scss
```

Any ideas on those (apparently unrelated) issues? Should I open a new issue on these?
