### ISSUE TITLE
Too long build

### ISSUE THREAD

**Issue by sagorshkov** [webpack/webpack#4550]
**Do you want to request a *feature* or report a *bug*?**

Probably it's bug...

**What is the current behavior?**

![2017-03-23 16 10 41](https://cloud.githubusercontent.com/assets/15627840/24244119/cdf2af46-0fe7-11e7-8866-2f1c682eef35.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
I build a simple example with one 'import' = angular library.
After update to 2.3.1 version I noticed that build is too long.

**What is the expected behavior?**

The **same** project with 2.2.1 webpack.

![2017-03-23 16 36 54](https://cloud.githubusercontent.com/assets/15627840/24244181/10eb93ee-0fe8-11e7-9d38-ea11904d29fd.png)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by jhnns** [comment]
Wow, that's a bad regression. Could you share the example with us? It would help us to track down the problem 👍

**Comment by piecyk** [comment]
Yeah, maybe it's connected... when updating from `2.2.1` to `2.3.0 | 2.3.1` something is of with `SourceMaps`
```js
new webpack.SourceMapDevToolPlugin({
  filename: '[file].map',
  columns: false
}),
```
 It takes way longer than on `2.2.1` on initial build and re-builds... will try to debug what is happening.

**Comment by kenborge** [comment]
My build too went from about 30 seconds to 120 seconds with 2.3.1

**Comment by ThomasRooney** [comment]
My initial build times initially increased significantly but mostly went back to normal with subsequent builds.

All build times for Dll modules were 4x(average of 22s instead of average 5s) 2.2.1 build times at first then went to within after a few rebuilds 1s of original [these lack source maps].
For our application bundle (with inline-source-map), build went from from 91s -> 88s.->68s (original was ~69s). So for my configuration it just looks like warming up the caches solved it.

[Using devtool: 'inline-source-map' and no explicit sourcemap plugins. Just many DllReferencePlugin's and very little else. ].

**Comment by sokra** [comment]
Looks like related to the cheap source map change.

**Comment by sokra** [comment]
Looks like big javascript files cause this with `cheap-source-map`.

**Comment by sokra** [comment]
![image](https://cloud.githubusercontent.com/assets/1365881/24268774/3ad0acb8-100f-11e7-8c11-5c1b0ec344ed.png)

Could be this line^^

**Comment by loganfsmyth** [comment]
Sounds like a similar issue to https://github.com/babel/babel/pull/3565 where because you read from `this.generatedCode`, V8 will flatten the string into contiguous memory on access. When concatenating a very large string, reading the string content should be avoided until you are done appending.

**Comment by TheLarkInn** [comment]
Thanks for the note @loganfsmyth

**Comment by sokra** [comment]
Great info, thanks @loganfsmyth

**Comment by mgol** [comment]
Is this fixed now? I removed `node_modules` & `yarn.lock` and re-run `yarn` and it's fast again without changing `package.json`.

**Comment by sokra** [comment]
yep fixes

**Comment by lechu1985** [comment]
I did the same as @mgol but I didn't solve the issue.
Build still hangs on `91% additional asset processing`  for quite a while (>90s). 

Using:
webpack@2.3.2
Angular@4.0.0

Windows 10
NodeJS: 6.9.4

**Comment by lumberj** [comment]
I see this issue on 2.3.3 if I run webpack with the `-p` flag

**Comment by btnwtn** [comment]
I am also experiencing this issue.

**Comment by thebarada** [comment]
I am also experiencing this issue on 2.5.1

**Comment by j-nord** [comment]
I have the same issue with webpack 2.60 => webpack.optimize.UglifyJsPlugin.
But we have in the package.json "syncfusion-javascript" a big minimize file. Is there a possible solution to easily integrate this in the packing process?

**Comment by nbolender** [comment]
Had this issue on 2.6.1 and it was making my build process basically impossible on production. I reverted to 2.4.1, which is a known working version for my setup.

**Comment by sokra** [comment]
This seem to be a different issue. When facing incorrect long build times try this:

Make sure to use the lastest node.js version.

Make sure to use the lastest webpack version.

``` js
node --inspect-brk node_modules/webpack/bin/webpack.js ...
```

In chrome open chrome://inspect

Open the devtools for node.js

Go to the profiler and start a CPU profile (it automatically continues execution):

![image](https://user-images.githubusercontent.com/1365881/26871283-f74fb3fe-4b72-11e7-975b-0f5853459a34.png)

Watch the commandline and press `Stop` when the build has finished.

Take a look at the flame graph. Take a screenshot. Identify slow parts.

![image](https://user-images.githubusercontent.com/1365881/26873277-8fa547e4-4b79-11e7-84f6-43eafe580a13.png)

Save the profile into a file.

File a new issue with your findings.

**Comment by fxck** [comment]
![image](https://user-images.githubusercontent.com/1303561/27222337-2034460c-528c-11e7-8124-3e8bcdba8003.png)

after about 10 minutes I end up with

![image](https://user-images.githubusercontent.com/1303561/27222373-4a890eb0-528c-11e7-8f42-3ceadfed96e5.png)

**Comment by medv** [comment]
Adding a swap drive will fix the above, for anyone landing here in the future, though has little to do with original issue:

https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04
