### ISSUE TITLE
scope hoisting - tried out and bundle gives multiple errors

### ISSUE THREAD

**Issue by lukeapage** [webpack/webpack#4909]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Bundle loads..

**What is the expected behavior?**

Bundle does not load when adding
```
        new webpack.optimize.ModuleConcatenationPlugin(),
```
on the next branch

This is against a large 160k line application using es6 modules and quite a few libraries, with 2 bundles code split out.

btw the size savings are 17kb out of 1496 kb which is good.

Errors are:

![image](https://cloud.githubusercontent.com/assets/309321/26305527/ee0fac52-3eef-11e7-8fc7-85e59d5e9b72.png)

![image](https://cloud.githubusercontent.com/assets/309321/26305542/039b0f3a-3ef0-11e7-9cfe-289ac9b6c140.png)

![image](https://cloud.githubusercontent.com/assets/309321/26305561/17f26636-3ef0-11e7-901d-c243f33608fe.png)

The project is not open source, so I can't just point you at it, but hopefully the above might help you.

If you want me to try anything specific, please comment.

Thanks for your efforts so far!

**Comment by lukeapage** [comment]
I wonder if it might be a circular dependency? We try not to have those, but it could be the case.. its hard to prevent.

**Comment by sokra** [comment]
Could you try to clear the babel-loader cache?

**Comment by lukeapage** [comment]
I can try, though I did save the URL in my package so it should have happened automatically. Will try tomorrow

**Comment by sokra** [comment]
fixed by #4884

**Comment by lukeapage** [comment]
@sokra please re-open - it fixes the exports is not defined, but the cannot read property call of undefined is still a problem

**Comment by lukeapage** [comment]
I'll debug a bit to see if I can work out why the error is occuring

**Comment by lukeapage** [comment]
![image](https://cloud.githubusercontent.com/assets/309321/26324295/877cde40-3f32-11e7-98c6-c290c4ee0499.png)

**Comment by lukeapage** [comment]
It seems module id 9 can't be found. 
When I look up the import:
![image](https://cloud.githubusercontent.com/assets/309321/26324566/9203eb00-3f33-11e7-8551-32a9ae5f9f0d.png)

and then find the code  in that import, its actually module id 11:
![image](https://cloud.githubusercontent.com/assets/309321/26324542/7d1b8c16-3f33-11e7-8ffc-635066365211.png)

Let me know if I can do anything to help you track this down.

**Comment by sokra** [comment]
Is this releated to Scope Hositing? Could you try to compile without the `ModuleConcatenationPlugin`?

What does the stats say is module 9? `--display-modules`

`--output-pathinfo` give some more metadata.

**Comment by lukeapage** [comment]
It works fine on 2.5.3, but I didn't try the next branch without scope hoisting. I will get back with details.

**Comment by lukeapage** [comment]
on the #next branch without ModuleConcatenationPlugin there is no error.

the output path info has no 9 in it..
```
Child
    chunk    {0} 0.appsplit.js (appsplit) 5.7 MB {1} [rendered]
      [701] ./js/src/modules/[redacted].js 226 bytes {0} [built]
     [1004] ./js/src/modules/[redacted].js 2.78 kB {0} [built]
     [1010] ./js/src/modules/[redacted].js 2.25 kB {0} [built]
     [1012] ./js/src/modules/[redacted].js 200 bytes {0} [built]
     [1014] ./js/src/modules/[redacted].jsx 476 bytes {0} [built]
     [1016] ./js/src/modules/[redacted] 2.96 kB {0} [built]
     [1017] ./js/src/modules/[redacted] 5.37 kB {0} [built]
     [1018] ./js/src/modules/[redacted] 3.17 kB {0} [built]
     [1021] ./js/src/modules/[redacted] 1.36 kB {0} [built]
     [1022] ./js/src/modules/[redacted] 1.58 kB {0} [built]
     [1030] ./js/src/modules/[redacted] + 1 modules 5.24 kB {0} [built]
     [1035] ./js/src/modules/[redacted] + 13 modules 48.6 kB {0} [built]
     [1038] ./js/src/modules/[redacted] + 3 modules 15.3 kB {0} [built]
     [1040] ./js/src/modules/[redacted] 11 kB {0} [built]
     [1055] ./js/src/modules/[redacted] + 29 modules 122 kB {0} [built]
         + 351 hidden modules
    chunk    {1} app.js (app) 2.53 MB {2} [initial] [rendered]
       [86] ./js/src/modules/[redacted] 2.56 kB {1} [built]
      [101] ./js/src/controllers/[redacted] 5.69 kB {1} [built]
      [103] ./js/src/modules/[redacted] 150 bytes {1} [built]
      [169] ./js/src/modules/[redacted] 3.49 kB {1} [built]
      [230] ./js/src/app/bundles/phone.js + 65 modules 255 kB {1} [built]
      [337] ./js/src/modules/workspace/modules.phone.js + 34 modules 112 kB {1} [built]
      [545] multi src/app/bundles/phone.js 28 bytes {1} [built]
      [597] ./js/src/app/[redacted] 404 bytes {1} [built]
      [598] ./js/src/app/[redacted] 275 bytes {1} [built]
      [617] ./js/src/app/[redacted] + 1 modules 1.99 kB {1} [built]
      [625] ./js/src/modules/[redacted] + 1 modules 1.44 kB {1} [built]
      [626] ./js/src/modules/[redacted]336 bytes {1} [built]
      [642] ./js/src/modules/[redacted] 733 bytes {1} [built]
      [649] ./js/src/modules/[redacted] 1.88 kB {1} [built]
      [650] ./js/src/modules/[redacted] + 5 modules 21 kB {1} [built]
         + 406 hidden modules
    chunk    {2} framework.js (framework) 2.16 MB [entry] [rendered]
        [0] ./node_modules/lodash/lodash.js 540 kB {2} [built]
        [2] ./js/src/modules/log/index.js 6.18 kB {2} [built]
       [19] ./js/libs/jqueryAll.js 234 bytes {2} [built]
       [35] (webpack)/buildin/module.js 495 bytes {2} [built]
       [38] ./js/src/modules/perfLog/sagas/perfLogActions.js + 2 modules 8.76 kB {2} [built]
       [66] ./js/src/modules/perfLog/perfLogNames.js 1.36 kB {2} [built]
      [158] ./node_modules/asap/browser-asap.js 2.18 kB {2} [built]
      [228] ./node_modules/yaku/lib/yaku.js 25.2 kB {2} [built]
      [229] ./js/libs/polyfills.js 543 bytes {2} [built]
      [231] ./js/src/framework/bundles/phone.js + 26 modules 50.7 kB {2} [built]
      [543] ./node_modules/whatwg-fetch/fetch.js 12.7 kB {2} [built]
      [544] multi libs/polyfills.js src/framework/bundles/phone.js 40 bytes {2} [built]
      [614] ./js/src/framework/framework.js + 10 modules 18.7 kB {2} [built]
      [641] ./js/src/modules/perfLog/perfLogging.js 9.1 kB {2} [built]
      [644] ./js/src/modules/[redacted] 1.69 kB {2} [built]
         + 224 hidden modules
       [0] ./node_modules/lodash/lodash.js 540 kB {2} [built]
       [2] ./js/src/modules/log/index.js 6.18 kB {2} [built]
     [158] ./node_modules/asap/browser-asap.js 2.18 kB {2} [built]
     [229] ./js/libs/polyfills.js 543 bytes {2} [built]
     [230] ./js/src/app/bundles/phone.js + 65 modules 255 kB {1} [built]
     [231] ./js/src/framework/bundles/phone.js + 26 modules 50.7 kB {2} [built]
     [337] ./js/src/modules/workspace/modules.phone.js + 34 modules 112 kB {1} [built]
     [544] multi libs/polyfills.js src/framework/bundles/phone.js 40 bytes {2} [built]
     [545] multi src/app/bundles/phone.js 28 bytes {1} [built]
     [546] ./js/src/app/bundles/phone.js 1.63 kB [built]
     [547] ./js/src/framework/bundles/phone.js 326 bytes [built]
    [1125] ./js/src/framework/initMaster.js 1.27 kB [built]
    [1282] ./js/src/modules/[redacted] 2.88 kB [built]
    [1290] ./js/src/modules/[redacted] 352 bytes [built]
    [1555] ./js/src/serviceWorker.js 332 bytes [built]
        + 1676 hidden modules
```

the import failing is this one:
```
import getOpenApi from 'src/framework/openApi';
```

which is id 12 (from the stats file..)

{"id":12,"identifier":"[redacted]\\node_modules\\babel-loader\\lib\\index.js??ref--0![redacted]\\js\\src\\framework\\openApi.js","name":"./js/src/framework/openApi.js"

and id number 9 which it is failing to load is some other file completely:

```
{"id":9,"identifier":"C:\\Projects\\Go\\Source\\Iit.SaxoTrader.App\\node_modules\\react-dom\\lib\\ReactDOMComponentTree.js","name":"./node_modules/react-dom/lib/ReactDOMComponentTree.js","index":319,"index2":308,"size":6270,"cacheable":true,"built":true,"optional":false,"prefetched":false,
```

I can send you the full stats file or any other debug output via a message on twitter and am also happy to help in any other way.

**Comment by sokra** [comment]
ok looks like a scope hoisting bug...

**Comment by sokra** [comment]
Could you try again with the latest `next` branch?

**Comment by lukeapage** [comment]
Same issue, but now on a different module id and its a different import causing the problem

![image](https://cloud.githubusercontent.com/assets/309321/26617256/742e9f1a-45d4-11e7-85db-57fc04046e2b.png)

**Comment by lukeapage** [comment]
Can I provide any additional information?

**Comment by lukeapage** [comment]
So sorry.. the issue is on my end. I was including a debug bundle build without scope hoisting.
