### ISSUE TITLE
BUG: Uncaught (in promise) Error: Loading chunk 0 failed.

### ISSUE THREAD

**Issue by johannes-z** [webpack/webpack#5264]
**Do you want to request a *feature* or report a *bug*?**

*Bug*

**What is the current behavior?**

I'm exporting using the `amd` `libraryTarget`. The sources use dynamic imports and my `webpack.config.js` has multiple entries. 

Loading the `output` entry file works fine, but the file itself loads the `fileA.js` file, resulting in this error: `Uncaught (in promise) Error: Loading chunk 0 failed.`

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a repo I created which shows the problem: https://github.com/johannes-z/webpack-test

**What is the expected behavior?**

The url of the `script.src` is correct (I double checked, opening the file in my browser and it was found).

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node: v7.7.0
webpack: v3.1.0

**Comment by johannes-z** [comment]
This only seems to happen, if I add `fileA.js` to the `entry` object. Removing it from there resolves the error.
The reason I explicitly added `fileA.js` to the `entry` object was to create the file even if it wasn't required by another source file.

**Comment by bigbigbigbear** [comment]
have you resolve this bug?i dont know how to resolve it

**Comment by johannes-z** [comment]
You can check what I did in my repo I've posted.

**Comment by antn9x** [comment]
I resolved by add publicPath: '/', to output in webpack, hope this help.

**Comment by blasterbug** [comment]
Got the same bug, adding `publicPath: '/'` to `output` does not fix the problem either. 
(webpack@4.11.1)

**Comment by victorhugorch** [comment]
This error maybe can occur because you forgotten or cancel run `ionic lab` on terminal and try to access any page. Give a look on this.

**Comment by IzaGz** [comment]
got same error
`Uncaught (in promise) Error: Loading chunk SideBarItemsEditing failed.
(missing: https://localhost:3000/page/2/js/Cunk-name.js)
    at HTMLScriptElement.onScriptComplete (app.js:130)`
when trying dynamic import with webpackPrefetch 
webpack 4.16

**Comment by ifelere** [comment]
For my own case I am using ionic embedded in a web app. The default build paths do not apply. I have an ant script that moves built assets+scripts to web app directory. I just now understood webpack chunks. I just had to tell webpack that my publicPath is different. In my case I use cross-env to pass a process.env.<FLAG> that I need  different publicPath (in custom webpack config for ionic) which I set to the root of my web app's public path and it solved my cased -- I also made sure I copied the generated chunk files too.  So, if you are in a situation like mine this may help.

**Comment by pelhage** [comment]
Anyone else still having this issue? I am seeing reports of this issue from users but am unable to reproduce. Have confirmed its not a network error though

**Comment by blasterbug** [comment]
@pelhage, I do seem that problem occurring sometimes. To me, it seems it is an issue with the worker trying to fetch _old_ chunks after updating the build. It's at least when I see this error happening (in production).
