### ISSUE TITLE
`webpack --watch` should write to stdout at the beginning and end of incremental build

### ISSUE THREAD

**Issue by ORESoftware** [webpack/webpack#5895]
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**What is the current behavior?**
`webpack --watch` does not write anything to stdout that would clearly indicate the current incremental build has (1) started or (2) is done/complete. See image attached.

**What is the expected behavior?**
I would expect, for the purposes of ecosystem tooling, that `webpack --watch` would write a clear message to stdout (1) when a file changed and (2) when it was done outputting the new result.

For example, `tsc --watch` writes this to stdout:
(1) "File change detected."
(2) "Compilation completed."

In this way, `tsc` allows ecosystem tooling to "hook into" `tsc -w`, and listen for stdout so as to hook into `tsc -w`. You can see the output from `tsc -w` in the picture below.

**If this is a feature request, what is motivation or use case for changing the behavior?**
The motivation is write better test runners that can run tests upon changes.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Here is `tsc -w` output:

<img width="577" alt="screenshot 2017-10-28 13 20 55" src="https://user-images.githubusercontent.com/11139560/32138156-24eeb144-bbe3-11e7-95c7-0021b746385d.png">

Here is `webpack -w` output:

<img width="623" alt="screenshot 2017-10-28 13 18 06" src="https://user-images.githubusercontent.com/11139560/32138164-324ca8a0-bbe3-11e7-8995-e615f94f8054.png">

As you can see, it's pretty much impossible to know when `webpack -w` has completed it's incremental build.

**Comment by ORESoftware** [comment]
It looks like the best thing I can do, to know when `webpack -w` is done creating an incremental build is to use some regex to match this output:

<img width="779" alt="screenshot 2017-10-28 13 28 27" src="https://user-images.githubusercontent.com/11139560/32138238-f8ec90f6-bbe3-11e7-913e-585363e2bb55.png">

But `webpack -w` still does not make it clear when the incremental build started. And of course this output is not that easy to parse.

**Comment by edvinv** [comment]
In vscode you must defined start/end pattern for background task, so that vscode knows when to parse output for errors. The problem is that there is no distinguished message generated after errors are written to output stream. Also there are situations where integration tools need to know when background task is running, so that, for example can wait to finish, before running debugger. 

It will be really good that webpack generates start/end messages when running in watch mode.  I think that webpack-dev-server already does this.

**Comment by ORESoftware** [comment]
@edvinv  so you are agree with me? I think it would help to make your statement a little more clear

**Comment by edvinv** [comment]
@ORESoftware, yes of course I agree with you. 

The biggest problem is end-message. I'm using vscode with ts-loader and currently there is no way to detect when webpack has ended background compiling. So I hope that start/end message will be added to webpack as it is already added to webpack-dev-server.

Also it will be nice that you configure start/end message text. This way I will be able to set same message as one generated from typescript compiler and from the point of vscode, webpack will behave exactly the same as tsc compiler.

**Comment by ORESoftware** [comment]
Ok cool thanks, yeah I use this regex to know when it's done compiling 

`/Asset*.Size*.Chunks/`

however, I would like a way to detect when webpack has _started_ it's incremental build. AND I think the stdout for starting/ending the incremental build should be more standardized.

Like I was saying, I would like this new feature hidden behind a flag:

`webpack --watch --machine-stdio`

this `--machine-stdio` flag will tell webpack to write JSON to stdout which can be parsed by processes that are reading from webpack's stdout.

**Comment by ORESoftware** [comment]
Here is the problem in short:

https://github.com/sumanjs/suman-watch-plugins/blob/master/modules/webpack/index.ts#L32

I don't have a regex that I can use, which can match against `webpack -w` stdout that will signal the start of an incremental build.

**Comment by sokra** [comment]
You can write a plugin that adds this behavior. Plugin into `invalid` and `done` hooks of the Compiler.

**Comment by the1mills** [comment]
This is for a library. All my users would then have to use a plugin in their webpack.config.js file. For my use case a flag would be better than a plugin, TBH.

**Comment by EugeneHlushko** [comment]
@sokra you should close this now

**Comment by eamodio** [comment]
Can this be reopened? This is a big issue for getting problem matchers to work in vscode. Especially if the webpack config returns more than 1 config. A simple message when it detected a file change, and another at the end of all the re-compiles.

**Comment by eamodio** [comment]
With start and end messages vscode problem matchers would work nicely. See https://github.com/TypeStrong/ts-loader/issues/660

**Comment by eamodio** [comment]
FYI, I just published [TypeScript + Webpack Problem Matchers](https://marketplace.visualstudio.com/items?itemName=eamodio.tsl-problem-matcher) for vscode that provides a set of problem matchers for `ts-loader` and `tslint-loader`

**Comment by edvinv** [comment]
This is still a problem even with using --info-verbosity verbose, because end message is not generated after all errors are shown to stdout, so it is not useful for using as vscode problem matcher.

For example, this is generated when error is reported using ts-loader:
```
Compilation starting…


Compilation finished

Hash: 9f5804b616b6b7ae6618
Version: webpack 4.17.2
Time: 1583ms
Built at: 2018-09-04 15:04:08
               Asset      Size           Chunks                    Chunk Names
./cmanager.js  3.28 MiB  cmanager  [emitted]  [big]  cmanager
 + 3 hidden assets
Entrypoint cmanager [big] = ./manifest.js ./vendor.js ../css/cmanager.css ./cmanager.js
[../cty/sys/data/comparer.ts] 574 bytes {cmanager} [built] [10 errors]
[../cty/sys/index.ts] 1.82 KiB {cmanager} [built]
    + 731 hidden modules

ERROR in /home/edvinv/repos/cty/sys/data/comparer.ts
../cty/sys/data/comparer.ts
[tsl] ERROR in /home/edvinv/repos/cty/sys/data/comparer.ts(5,21)
      TS1005: '(' expected.

```
I would expect that all outputs would be wrapped inside 'Compilation starting…' and 'Compilation finished', but this is not the case.

**Comment by eamodio** [comment]
Yeah -- to really get things to work properly (as far as I can tell), webpack would need to move the `Compilation finished` (or `Compilation X finished` when using multiple configs) message AFTER any output errors. Without that, I don't see how to get a reliable matcher.

**Comment by eamodio** [comment]
Please don't close this. It is needed for better problem matcher support in vscode

**Comment by evilebottnawi** [comment]
@eamodio what your problem? Please create minimum reproducible test repo with what you actually have and what you expected

**Comment by evilebottnawi** [comment]
bump

**Comment by alexander-akait** [comment]
webpack-cli@4 writes these messages to `stderr`  (because `stdout` for stats), starting and ending compilation are diagnostic information and it should be write in `stderr`, you can see this messages using https://webpack.js.org/configuration/other-options/#infrastructurelogging (level: 'log'), anyway if you still need something more please open an issue in webpack-cli and we will found a way to help you, nothing to fix in webpack
