### ISSUE TITLE
[4] Webpack turns "this" to undefined in class definitions

### ISSUE THREAD

**Issue by drcmda** [webpack/webpack#6379]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

See https://github.com/webpack/webpack/issues/6357#issuecomment-360308225 and https://github.com/babel/babel/issues/7264

Webpack turns the method in this code:

```js
import React from 'react'

class A {
    constructor() {
        this.b = 1
    }
    method(a = this.b) {
        console.log(a)
    }
}
```

into

```js
    method(a = undefined.b) {
        console.log(a)
    }
```

probably confusing the top-level with class-level. Curiously without the import (any import) it seems to be fine.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

MacOS High Sierra, Node 9.4.0, Webpack 4 beta.0

**Comment by TheLarkInn** [comment]
This has been fixed with #6380 by @ooflorent

**Comment by drcmda** [comment]
@TheLarkInn @sokra is this in 4.0.0-beta.1 ? It still doesn't seem to work ...

**Comment by ooflorent** [comment]
@drcmda Could you have a look at https://github.com/webpack/webpack/pull/6380/files#diff-01500706b1ed8ba9c79ef1fb8489c553R25? I've added a test (which passes). Maybe you're encountering another issue. Could you create minimal reproducible sample?

**Comment by drcmda** [comment]
@ooflorent it's the same as above. If you just run it without an import statement above, it works. But the moment you have an import, it's back to undefined.

```js
import React from 'react' // <---- this is important

class A {
    constructor() {
        this.foo = 1
    }
    method(arg = this.foo) {
        console.log(arg)
    }
}

new A().method()
```

**Comment by drcmda** [comment]
@ooflorent there's another thing that's curious, it only happens with the following setup:

```
const options = {
    presets: [
        ['@babel/preset-env', { modules: false, /*useBuiltIns: 'usage'*/ targets: { browsers: 'last 2 Chrome versions' } }],
    ],
    plugins: [
        '@babel/plugin-transform-classes',
    ],
}
```

**Comment by ooflorent** [comment]
`import` instructs webpack to run the plugin that convert `this` into `undefined`. Since you are applying babel’s transforms it probably conflicts with one of them because the plugin is ran after Babel.

**Comment by sqal** [comment]
Hi guys. Has this issue been fixed in webpack 4? I just upgraded my project to Webpack 4.5.0 and this problem appears to be still present (in any webpack 4 version).

Here's a reproduction - https://github.com/sqal/webpack-4-bug-reproduction. Run `npm run build` and  check the output in build/app.js. You can see that in Class example,  `this` in default parameter value is kept as expected, but in action example, where i export just an object with some function, `this` is still replaced with undefined.

I would appreciate if someone could take a look at it Thanks :)

**Comment by ooflorent** [comment]
I'll try to fix this.

**Comment by tatobari** [comment]
Sorry for jumping in without any contributions. This issue looks pretty alive and I might be having the same issue.

Could this be the reason why some bundles I'm importing, [SwiperJS ESM Bundle](https://github.com/nolimits4web/swiper/blob/master/dist/js/swiper.esm.bundle.js), for example, read `undefined` once compiled where the original files read `this`? This began happening as soon as I've updated to Webpack 4.

**Comment by ooflorent** [comment]
I’ve opened a PR with a fix. Everything should be back to normal once it would be merged.

**Comment by OndrejPiza** [comment]
Hi,

I know it is closed, but I have similiar issue. In ctor, "this" is undefined. I have webpack from master branch. 

"-- webpack@4.5.0  (github:webpack/webpack#55fb1da1935c44ebbe5e274a4f785eeaa79a3125)" - which is the last commit.

**Comment by ooflorent** [comment]
@OndrejPiza this has been fixed on master and not released yet. If you still encounter a bug, please open a new issue with a reproduction example.

**Comment by OndrejPiza** [comment]
@ooflorent Sorry, my bad, mistake was somewhere else. Now it's wokring.

**Comment by kamalendugarai** [comment]
@ooflorent Has this been released in current webpack version. My webpack version is 4.29.0 and the same thing happening to me.

**Comment by ifeltsweet** [comment]
This is still happening with v4.30.0

**Comment by evilebottnawi** [comment]
you still have old webpack package, maybe you use global webpack installation

**Comment by ifeltsweet** [comment]
After a bit of reading I think this is Babel to blame - https://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined-and-inserting-use-str
