### ISSUE TITLE
[ext] placeholder is not replaced when set in output.filename

### ISSUE THREAD

**Issue by hparton** [webpack/webpack#6753]
**Do you want to request a *feature* or report a *bug*?**

~~Bug~~ feature

**What is the current behavior?**

Using '[ext]' placeholder in the output.filename doesn't get replaced and instead you get a file with 'filename.[ext]'.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just setting the config to the following is enough:
```js
output: {
    filename: '[name].[hash].[ext]'
}
```

**What is the expected behavior?**

'[ext]' should be replaced with the relevant extension.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node Version: 8.9.4
Webpack Version: 4.1.1

**Comment by ooflorent** [comment]
@sokra This placeholder exists in `file-loader`. Would it be a good idea to support it in webpack? This would allow the devs to do the following:

```css
{
  entry: {
    main: "./main.js",
    styles: "./styles.css",
  },
  output: {
    filename: "[name].[contenthash].[ext]",
  }
}
```

It could be useful if webpack would handle other module types in the future.

Another use case could be:

```css
{
  entry: {
    legacy: "./legacy.js",
    modern: "./modern.mjs",
    //                ^
  },
  output: {
    filename: "[name].[ext]",
  }
}
```

**Comment by michael-ciniawsky** [comment]
Supporting `[ext]` would be awesome to avoid extra props like `cssFilename: '[name].css'` or the like in the future, but this may require a whitelist of valid `output` extensions for mapping common transpiler extensions to `'.html', '.css', '.js' && '.wasm'` based on their category, which is eventually inconvenient to maintain.... ? On the other hand transpiler usage is slowly declining and there weren't any new ones popping up for a while, so maybe it's fine :) 

**webpack.config.js**
```js
{
   entry: {
      'a': [ './a.ts', './a.tsx', './a.jsx', './a.coffee', ... ] // (?)
      'b': [ './b.scss', './b.less', './b.styl', ... ] // (?)
      'c': [ './c.pug', './c.hbs', './c.haml' ... ]  // (?)
      'd': './d.js',  ✅ 
      'e': './e.css', ✅ 
      'f': './f.html'  ✅
   },
   output: {
      filename: '[name].[contenthash].[ext]',
      chunkFilename: '[name].[contenthash].[ext]'
   }
}

**Comment by hparton** [comment]
Ah, I must have been confused with file-loader then, although there is this issue [#4276] referencing it as a regression in Webpack 2.

**Comment by glen-84** [comment]
The bot probably shouldn't close issues that are labelled.

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
bump

**Comment by akoidan** [comment]
This is not fixed!

**Comment by alexander-akait** [comment]
Use `fullhash` or `contenthash`

**Comment by akoidan** [comment]
@alexander-akait please provide an example: with` "webpack": "4.41.2",` I get
and `filename=[contenthash]` i don't get exntesions it's just `0.5100f6a4c6ba3a6b28f1`

**Comment by alexander-akait** [comment]
Update webpack v4 to the latest stable, also fixed in webpack@5

**Comment by akoidan** [comment]
@alexander-akait I updated webpack to the latest version, which is `4.46.0`. It has exactly the same behaviour I get files like `vendors~amchart.48332da493886b0679a9.[ext]`. I can NOT use webpack `5.x` since I have a lot o configuration around my current versions and plugins that don't support webpack5.

**Comment by alexander-akait** [comment]
Do not use `[ext]` in this case, just write `.js`

**Comment by akoidan** [comment]
omg... I didn't think of it. So simple solution. I guess my issue is resolved. Actually I see now that webpack doesn't support [ext](https://v4.webpack.js.org/configuration/output/#outputfilename) for output, but supports for other pars, which confuses some people.

**Comment by alexander-akait** [comment]
Yep, but we fix it in webpack@5

**Comment by cizario** [comment]
**webpack v5.35.1**
```
output: {
  filename: 'js/[name][ext]',
}
```
webpack 5 still don't recognize `[ext]` template and output file with `[ext]`.

@alexander-akait would you tell us the right way to use `[ext]` ?

**Comment by JakobJingleheimer** [comment]
@alexander-akait this appears to be broken: `filename: '[name][ext]'` results in `[ext]` literally in the output filename.

My problem is that all but a small number of files start and end as ESM (so package.json's `type` is set to `module`), but the others are commonjs, so their file extension is `.cjs`. That needs to persist, but webpack blindly replaces all of them with just `.js`.

**Comment by alexander-akait** [comment]
filename never support `[ext]`, just use `.mjs` in you case, you can't have `js` files with commonjs and EC modules in one repo

**Comment by JakobJingleheimer** [comment]
@alexander-akait the docs include `[ext]`: https://webpack.js.org/configuration/output/#outputchunkfilename

CJS is the exception, so it would make far more sense to use that different/special file extension for the small number (2) of special cases rather than the hundreds of other (ESM) files. Also, mjs is not valid outside of node (and the cjs files are exclusive to the node part of the app).

Are you saying cjs & esm can't be in the same repo is a webpack limitation, or a general limitation? (Cuz in general, you absolutely can have both commonjs and esm in the same repo 🙂)

**Comment by alexander-akait** [comment]
@JakobJingleheimer I don't understand your problem, please provide example

**Comment by JakobJingleheimer** [comment]
```
my-electron-app/
  backend/
    app.js
    index.cjs
    …
  frontend/
    index.js
    App.jsx
    …
```

`my-electron-app/backend/index.cjs` is a hack around Electron detecting esm and arbitrarily sh*tting the bed (it would actually work just fine if they just got out of the way because node supports loading commonjs in ESM). That file is commonjs and tricks Electron's detection code. Anything that needs Electron dependency injected must be a commonjs file, but there are only like 2 places where that's needed. Everything else is ESM and runs just fine when webpack isn't overly helpful replacing very intentional file extensions.

**Comment by alexander-akait** [comment]
Do you need to use `.js` in one directory and `.cjs` in other? But `[ext]` will not help your here...

**Comment by JakobJingleheimer** [comment]
No, but the `.cjs` files occur in only the `backend` directory (but  there are non-cjs files in there too).

In the frontend directory, `.jsx` should be replaced with `.js`.

**Comment by alexander-akait** [comment]
But how webpack should understated this?

**Comment by JakobJingleheimer** [comment]
Yes, fair question.

I have 2 different webpack configs (and npm tasks), one for backend and one for frontend. In the backend one, I just want to (effectively) disable replacing the file extension (use whatever the original was).

**Comment by alexander-akait** [comment]
Just specify file extension in `filename` for backend and other value for frontend

**Comment by JakobJingleheimer** [comment]
The whole problem is that the file extension cannot be blindly set to an arbitrary value for everything.

The workaround I mentioned above:

```js
// backend/webpack.config.cjs

module.exports = {
  …
  output: {
    filename({ chunk: { name } }) {
      const ext = cjsFiles.has(name)
        ? '.cjs'
        : '.js';

      return `${name}${ext}`;
    }
  },
};
```

**Comment by alexander-akait** [comment]
How you detect `cjsFiles`?

**Comment by JakobJingleheimer** [comment]
> I've used filename as a function and check chunk.name for a match against hardcoded values

I don't—I think I can't because webpack does not expose the information I need to do so; if the original extension was available in filename()'s argument, I could use that, but it's not. So, cjsFiles is a hardcoded list that is in no way connected to the actual file names (which is not ideal):

```js
const cjsFiles = new Set(['main', '…']);
```

I could do something like recursively look for all `.cjs` files in the directory and build a list from that, but that seems over-engineered for ~2 files.

**Comment by mozhs** [comment]
> There is no such placeholder

<img width="1027" alt="截屏2021-06-28 下午11 09 37" src="https://user-images.githubusercontent.com/11417330/123660740-7ff5a180-d866-11eb-8f85-cfa29146355d.png">

Putting [ext] in Output related configuration items in the document can easily mislead developers. As of 2021-06, there are still people who are misled by this document, which is enough to show that the document needs to be considered.

> 文档里面把 [ext] 放在 Output 相关配置项中，非常容易误导开发者。时至 2021-06 仍有人被这份文档误导，足以说明文档有需要斟酌的地方。

**Comment by JakobJingleheimer** [comment]
Yes, this is what mislead me.

Also very strange that it is absent in the ones available to filename (which has all? others)

**Comment by SkylineHR31** [comment]
And how I can make two and more bundles for .css .js etc.?
