### ISSUE TITLE
Bunyan errors

### ISSUE THREAD

**Issue by bitplanets** [webpack/webpack#689]
Module not found: Error: Cannot resolve module 'fs' in node_modules\bunyan\node_modules\mv\node_modules\mkdirp

What should I do?

**Comment by jhnns** [comment]
Bunyan is using the browserify way to [conditionally require a node-only module](https://github.com/trentm/node-bunyan/blob/2f95bb8091a8085756cc1f73c51dcf020f1990a2/lib/bunyan.js#L33-38). This approach doesn't work with webpack, because webpack is able to resolve simple expressions like `'dtrace-provider' + ''` statically.

My suggestion is to [alias](http://webpack.github.io/docs/configuration.html#resolve-alias) the `dtrace-provider`-module with a small module that throws an error when required:

```javascript
// webpack.config.js
    ...
    resolve: {
        "dtrace-provide": path.resolve(__dirname, "./path/to/dtrace-shim.js")
    }
```

```javascript
// dtrace-shim.js
throw new Error("dtrace is not available in the browser");
```

**Comment by bitplanets** [comment]
Actually there were some typos, but figured out:

        alias: {
            "dtrace-provider" : absPath("other_modules/dtrace-shim"),
            "fs"              : absPath("other_modules/fs-shim"),

fs-shim.js is just an empty file.

I don't really like this solution, is kind of bad. Also because on the server side I use webpack with enhanced require so the "fs" will bre replaced by the fs-shim, right? And might break other stuff.

**Comment by sokra** [comment]
There is a better way which works with webpack and browserify, but it requires changes to the module:

``` js
// package.json
"browser": {
  "dtrace-provider": false,
  "fs": false
}
```

``` js
var dtrace = require('dtrace-provider'); // will return an empty object for the browser
```

And you need to change a few lines that tests for `dtrace` (it's now `{}` instead of `null`).

**Comment by bitplanets** [comment]
I have to change the package.json of bunyan? I can't do that, because in production the npm install will not do that automatically.

Also the dtrace should throw an error for the bunyan lib to work. They try to load and in browserify throws an error, and they use that behaviour to check.

**Comment by sokra** [comment]
> but it requires changes to the module:

Yeah, you need to do a PR.

**Comment by sokra** [comment]
If you don't want to do that, use the approach @jhnns suggested, or the `IgnorePlugin`.

**Comment by bitplanets** [comment]
Thanks

**Comment by trentm** [comment]
Should be fixed with bunyan v1.5.0. Sorry for my delays.

**Comment by pheuter** [comment]
Still getting `Cannot resolve module fs` errors for bunyan v1.5.1:

```
ERROR in ./~/bunyan/~/mv/~/rimraf/rimraf.js
Module not found: Error: Cannot resolve module 'fs' in /Users/markfayngersh/qh-pcp-client/node_modules/bunyan/node_modules/mv/node_modules/rimraf
 @ ./~/bunyan/~/mv/~/rimraf/rimraf.js 6:9-22

ERROR in ./~/bunyan/~/mv/index.js
Module not found: Error: Cannot resolve module 'fs' in /Users/markfayngersh/qh-pcp-client/node_modules/bunyan/node_modules/mv
 @ ./~/bunyan/~/mv/index.js 1:9-22

ERROR in ./~/bunyan/~/mv/~/mkdirp/index.js
Module not found: Error: Cannot resolve module 'fs' in /Users/markfayngersh/qh-pcp-client/node_modules/bunyan/node_modules/mv/node_modules/mkdirp
 @ ./~/bunyan/~/mv/~/mkdirp/index.js 2:9-22

ERROR in ./~/bunyan/lib/bunyan.js
Module not found: Error: Cannot resolve module 'fs' in /Users/markfayngersh/qh-pcp-client/node_modules/bunyan/lib
 @ ./~/bunyan/lib/bunyan.js 31:13-26

ERROR in ./~/bunyan/~/mv/~/rimraf/~/glob/glob.js
Module not found: Error: Cannot resolve module 'fs' in /Users/markfayngersh/qh-pcp-client/node_modules/bunyan/node_modules/mv/node_modules/rimraf/node_modules/glob
 @ ./~/bunyan/~/mv/~/rimraf/~/glob/glob.js 43:9-22

ERROR in ./~/bunyan/~/mv/~/rimraf/~/glob/sync.js
Module not found: Error: Cannot resolve module 'fs' in /Users/markfayngersh/qh-pcp-client/node_modules/bunyan/node_modules/mv/node_modules/rimraf/node_modules/glob
 @ ./~/bunyan/~/mv/~/rimraf/~/glob/sync.js 4:9-22

ERROR in ./~/bunyan/~/mv/~/ncp/lib/ncp.js
Module not found: Error: Cannot resolve module 'fs' in /Users/markfayngersh/qh-pcp-client/node_modules/bunyan/node_modules/mv/node_modules/ncp/lib
 @ ./~/bunyan/~/mv/~/ncp/lib/ncp.js 1:9-22
```

**Comment by oojacoboo** [comment]
Same issue as @pheuter on 1.8.1.  Did you get a solution to that @pheuter?

**Comment by bebraw** [comment]
@oojacoboo If you feel this is a bug, could you open a separate issue? The issue template guides with that.
