### ISSUE TITLE
Modules is missing in production mode

### ISSUE THREAD

**Issue by yangmingshan** [webpack/webpack#7499]
# Bug report
Maybe same problem with #7425

**What is the current behavior?**
Seems some modules is missing in production mode

**If the current behavior is a bug, please provide the steps to reproduce.**
It's hard to create a minimum reproducible example (I tried, I can't upload our project). But there has call stack trace:

![image](https://user-images.githubusercontent.com/13585043/41086858-d4bced1e-6a6d-11e8-93f0-42b81460a048.png)

![image](https://user-images.githubusercontent.com/13585043/41086863-d8419c6e-6a6d-11e8-98ed-bf6e655bd45c.png)

![image](https://user-images.githubusercontent.com/13585043/41086868-db33b100-6a6d-11e8-8ad5-d5bca90a9e27.png)

**What is the expected behavior?**
Not missing any module

**webpack config**
vue-cli v3.0.0-beta.15 default config

**Other relevant information:**
webpack version:  v4.11.1
Node.js version: v10.4.0
Operating System: macOS High Sierra 10.13.5

**Comment by sod** [comment]
Is there any library that has sideEffects: false configured?

```sh
grep sideEffects node_modules/*/package.json
```

**Comment by yangmingshan** [comment]
@sod Yes, I found in `rxjs`. But I'm not using `rxjs`, it's a dependency for `lint-staged` (lint-staged -> listr -> rxjs). And the missing module is our component, not some library.

**Comment by yangmingshan** [comment]
I try to remove `lint-staged`, and it has same problem (of course). Seems we are different problem.

**Comment by sokra** [comment]
Hi @yangmingshan it difficult to see the problem from your screenshots, but here are some hints that may help you to find the problem:

* Disable HashModules and enable namedModules. This should make it easier to read the stuff as modules have useful names.
* Disable minimizing. This should make it easier to read the source.
* function for module 6jJR doesn't seem to be loaded. Check from the stats in which chunk this module is.
* There are 3 possible cases: The chunk should be loaded but isn't. The module is not in the right chunk. The module isn't in any chunk at all.

**Comment by yangmingshan** [comment]
@sokra Seems the module isn't in any chunk at all, I only found two `__webpack_require__("6jJR")` call in all build files.

![image](https://user-images.githubusercontent.com/13585043/41154470-d8d79d56-6b4c-11e8-9582-8783901cf5a6.png)

And how to disable HashModules and enable namedModules? I tried `optimization.namedModules`, not work.

I will keep trying create a minimum reproducible example.

**Comment by dlebedynskyi** [comment]
I think we are running into same issue. On production build for 2 chunks only we are seeing 
![image](https://user-images.githubusercontent.com/1182917/41239743-de10f936-6d66-11e8-8efc-cd51b5da17c7.png)

![image](https://user-images.githubusercontent.com/1182917/41239809-02db32ae-6d67-11e8-99e9-0c6cc5696dee.png)

it looks a in  manifest is sparse  array for some reason. 

@sokra  Anything I can help to debug this issue from my side? This started after we updated form 4.10.2 to 4.11

**Comment by bradleyayers** [comment]
I might be experiencing the same bug. In my case I think the problem is that there's a `__webpack_require__(…)` that **shouldn't** be there.

I have this source file: (`./node_modules/@heydovetail/ui-components/lib.es2015/components/Link/index.js`)

```js
import * as rrd from "react-router-dom";

export const Link = React.createContext(rrd.Link);
//# sourceMappingURL=index.js.map
```

In the production build it's compiled to:

```js
// EXTERNAL MODULE: ./node_modules/react-router-dom/es/Link.js
var es_Link = __webpack_require__(274);
// CONCATENATED MODULE: ./node_modules/@heydovetail/ui-components/lib.es2015/components/Link/index.js
/* harmony import */
__webpack_require__(/*! react-router-dom */
76);
const Link_Link = React.createContext(es_Link.a);
//# sourceMappingURL=index.js.map
```

The error is thrown inside `__webpack_require__(/*! react-router-dom */ 76);`:

```
TypeError: Cannot read property 'call' of undefined at __webpack_require__ (http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:20:27) at Module.9 (http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:6550:21) at __webpack_require__ (http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:20:27) at Object.580 (http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:6134:182) at __webpack_require__ (http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:20:27) at Object.581 (http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:6151:115) at __webpack_require__ (http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:20:27) at 0 (http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:82:16) at http://localhost:3000/packs/collector-194eaf08eb5776b1dae1.js:85:9
```

What's interesting is that:

1. The import is unused (only `Link` from `react-router-dom` is actually used, the root module is not, so it's a surprise that `react-router-dom` is being imported).
2. `react-router-dom` has `pkg.sideEffects=false`
3. It appears correct that `react-router-dom` is not available. The problem really seems that it's being imported at all.

My `optimization` portion of my webpack config:

```js
module.exports.optimization = {
  minimizer: [
    new UglifyJsPlugin({
      sourceMap: false,
      uglifyOptions: {
        compress: {
          dead_code: false,
          inline: false,
          side_effects: false,
          sequences: false,
          keep_fnames: true,
          keep_fargs: true,
          reduce_funcs: false,
          switches: false
        },
        mangle: false,
        output: {
          comments: "all"
        }
      }
    })
  ]
};
```

**Comment by princemaple** [comment]
I have the same problem and the `optimization: { sideEffects: false }` solution/workaround works for me, thanks @bradleyayers 

Is it a bug that we need to set this setting? 4.9.2 works without the said setting.

**Comment by mgol** [comment]
I've just hit it in an Angular CLI 6.0.8 + Angular 6.0.4 app. With NamedModulesPlugin enabled I see the following linew on the stack trace:
```js
/* harmony import */ var tslib__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("./node_modules/tslib/tslib.es6.js");
/* harmony import */ var rxjs__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__("./node_modules/rxjs/_esm5/index.js");
/* harmony import */ var rxjs__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__("./node_modules/rxjs/_esm5/internal/Subscription.js");
/* harmony import */ var rxjs__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__("./node_modules/rxjs/_esm5/internal/Subject.js");
/* harmony import */ var rxjs__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__("./node_modules/rxjs/_esm5/internal/Observable.js");
/* harmony import */ var rxjs__WEBPACK_IMPORTED_MODULE_5__ = __webpack_require__("./node_modules/rxjs/_esm5/internal/observable/merge.js");
/* harmony import */ var rxjs_operators__WEBPACK_IMPORTED_MODULE_6__ = __webpack_require__("./node_modules/rxjs/_esm5/operators/index.js");
/* harmony import */ var rxjs_operators__WEBPACK_IMPORTED_MODULE_7__ = __webpack_require__("./node_modules/rxjs/_esm5/internal/operators/share.js");
```

If you look at the file from which it comes, i.e. `node_modules/@angular/core/fesm5/core.js`, you'll see:
```js
import { __assign, __extends, __read, __spread, __values } from 'tslib';
import { Observable, Subject, Subscription, merge } from 'rxjs';
import { share } from 'rxjs/operators';
```

The failure is in the line importing `./node_modules/rxjs/_esm5/operators/index.js` - this file just requires all the operators from its directory so it seems it should be stripped out due to the `sideEffects` flag. The `require` to it stays, though, causing missing module errors which break the whole app.

It's not entirely clear what triggers the issue as it started appearing when I migrated my project's RxJS imports to this new format already used by `@angular/core` - and yet the error comes from `@angular/core` and not my own code.

**Comment by mgol** [comment]
FWIW, in my case changing:
```ts
import { pairwise, filter, take } from 'rxjs/operators';
import { merge } from 'rxjs';
```
in one file (`app.component.ts`) to the following:
```ts
import { filter, take } from 'rxjs/operators';
import { pairwise } from 'rxjs/operators/pairwise';
import { merge } from 'rxjs';
```
made the app work again. I suspect this may be pretty random...

**Comment by mgol** [comment]
@dlebedynskyi 
> Update: after some digging - looks like webpack 4.9.2 is fine, but 4.10.0 breaks.

I have tested `4.9.2` where it worked and `4.10.2` where it didn't so it seems probable that this is a `4.10.0` regression.

**Comment by henrist** [comment]
I hit the same issue when upgrading webpack in our project, where it failed when loading modules from redux-form. It breaks from 4.9.2 to 4.10.0.

@sokra It seems having a package that has `sideEffects: false` containing wildcard import breaks in combination with dynamic imports:

```js
import * as constants from './constants'
export { constants }
```

```js
import 'some-package'
import('./lazy')
console.log('this message is never seen')
```

lazy.js:
```js
import { constants } from 'some-package'
console.log('constants', constants)
```

I put up a minimal case to reproduce: https://github.com/henrist/webpack-module-missing-bug

**Comment by zahlio** [comment]
We had kind of the same error as here and #7425 

We tried:
`optimization.sideEffects = false`
Different version of webpack: 4.10.0, 4.12.0, 4.9.2

But nothing worked as the error message was kind of generic: `TypeError: Cannot read property 'call' of undefined`

We then did: 
```javascript
module.exports.optimization = {
  minimize: false
};
```

And found out the error was:

We then changed the following lines of code:
```javascript
export const unbind = Mousetrap.unbind; 
```
to

```javascript
export const unbind = (combination: Array<string>) => Mousetrap.unbind(combination); 
```
So just as @mgol the real error was random, but  the real question here is why webpack did not provide an error in development mode?

**Comment by bradleyayers** [comment]
@zahlio what was the compiled code in `mousetrap.js:934`?

**Comment by dlebedynskyi** [comment]
@henrist 
> I hit the same issue when upgrading webpack in our project, where it failed when loading modules from redux-form. It breaks from 4.9.2 to 4.10.0
this seem to be same issue for us. redux-froms is used in chunk that break for us as well.

**Comment by dlebedynskyi** [comment]
@sokra  test with 4.12.1  issue is still happening.

**Comment by sokra** [comment]
ok next try. #7499 should fix the problem in the repro from @henrist. It's a different problem to the problem by @yangmingshan.

@dlebedynskyi @zahlio Not sure if this is the same problem. Please provide a repro repo to get it fixed.

**Comment by dlebedynskyi** [comment]
@sokra  [#7499](https://github.com/webpack/webpack/issues/7499) seems to work for us as well. Tested our code against latest master. Thank you for fix.

**Comment by henrist** [comment]
Things are working properly from master here too. Thanks :)

**Comment by yangmingshan** [comment]
My problem is fixed in v4.12.1. Thanks

**Comment by davidlygagnon** [comment]
I ran into this exact same issue with Webpack 4.12.0.

I'm importing a library with free side-effects `sideEffect: false`.

The call in one of the main files is:
```
import {IconSettings} from '@salesforce/design-system-react';
```

When translated to webpack it looked like this:

![screen shot 2018-09-06 at 10 32 28 am](https://user-images.githubusercontent.com/1821787/45174643-3d97dd00-b1c0-11e8-9852-2f33ff520f0f.png)

where the first call tries to import the index.js of all modules supported in the library, `__webpack_require('306')`

However, 306 is missing in `modules`, for a reason.

<img width="184" alt="screen shot 2018-09-05 at 10 59 30 pm" src="https://user-images.githubusercontent.com/1821787/45174666-4e485300-b1c0-11e8-9cfe-e9bc9fc0bf7b.png">

That results into this error, which blows up the entire app.

![screen shot 2018-09-06 at 10 32 47 am](https://user-images.githubusercontent.com/1821787/45174657-48527200-b1c0-11e8-99a9-12ccb3a39d73.png)

I was able to fix it by upgrading to 4.12.2 (fixed in that [version](https://github.com/webpack/webpack/releases/tag/v4.12.2)).

Setting `optimizations.sideEffects: false` as @bradleyayers worked too but it was probably a temporary fix.

**Comment by kleingtm** [comment]
For what it's worth, I was running into this as well, and sideEffects: false did not fix it. I was using Vue CLI 3 TypeScript template and the error was caused by splitChunks:
```
optimization: {
...,
   splitChunks: {
      cacheGroups: {
        vendors: {
          name: 'chunk-vendors',
          test: /[\\\/]node_modules[\\\/]/,
          priority: -10,
          chunks: 'initial'
        },
        common: {
          name: 'chunk-common',
          minChunks: 2,
          priority: -20,
          chunks: 'initial',
          reuseExistingChunk: true
        }
      }
    },
...
}
```

I fixed by adding the following to `vue.config.js` to remove the splitChunks config:
```
	chainWebpack: config => {
		if (process.env.NODE_ENV === 'production') {
			config.optimization.sideEffects(false);
			config.optimization.delete('splitChunks');
		}
	},
```
