### ISSUE TITLE
Invalid ES6 code generated

### ISSUE THREAD

**Issue by apokryfos** [webpack/webpack#7551]
# Bug report

**What is the current behavior?**
When running with minification (default `optimize: true` flag) there is invalid JavaScript code produced with certain ES 6 codes. 

**If the current behavior is a bug, please provide the steps to reproduce.**

I have the following code:

```
    'use strict';
    
    Object.defineProperty(exports, "__esModule", {
        value: true
    });
    const config = {
        logLevel: 'i'
    };
    const logLevels = {
        a: 0, b: 1, c: 2, d: 3, e: 4, f: 4, g: 5
    };
    
    const shouldLog = (level, priority) => {
        const levelPriority = logLevels[level] || -1;
        const logPriority = logLevels[priority];
        return logPriority <= levelPriority;
    };
    
    const LoggerFor = exports.LoggerFor = (minLevel = null) => {
        const proxy = new Proxy(console, {
            get: (obj, prop) => {
                let fn = function noop() {};
                let realProp = prop;
                if (prop === 'v' || typeof obj[prop] !== 'function') {
                    realProp = 'l';
                }
                const level = minLevel || config.logLevel;
                if (shouldLog(typeof obj[prop] !== 'function' ? 'log' : prop, level)) {
                    fn = obj[realProp];
                }
                return (message, ...args) => fn(message, ...args);
            }
        });
        return proxy;
    };
```

This code is generated from my original code using babel but what I've shared here is the actual generated code so babel is not required to reproduce this issue. 

This is the (pretty-printed) code that this function generates. 

    "use strict";
    Object.defineProperty(t, "__esModule", { value: !0 });
    const r = "i", o = { a: 0, b: 1, c: 2, d: 3, e: 4, f: 4, g: 5 };
    t.LoggerFor = ((e = null) => {
        return new Proxy(console, {
            get: (t, n) => {
                let u = function () {
                }, f = n;
                "v" !== n && "function" == typeof t[n] || (f = "l");
                const i = e || r;
                return i = "function" != typeof t[n] ? "log" : n, o[i] <= (o[i] || -1) && (u = t[f]), (e, ...t) => u(e, ...t)
            }
        })
    });

The issue is the lines:
```
const i = e || r;
return i = "function" != typeof t[n] ? "log" : n, o[i] <= (o[i] || -1) && (u = t[f]), (e, ...t) => u(e, ...t)
```

This is reassigning to a `const` which is not allowed.

I am using the following webpack.config.js

```
module.exports = {
    entry: "dist/handler.js",
    target: 'node',
    resolve: {
        modules: [__dirname, 'node_modules']
    }
};

```

**What is the expected behavior?**

I would expect to get valid ES6 code. I'm not sure exactly how that code would look like though.

**Other relevant information:**
webpack version:  4.12
Node.js version:  8.11.1
Operating System: Ubuntu 18.04

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by apokryfos** [comment]
Hello @montogeek  thanks for your response. 

I've created https://github.com/apokryfos/webpackissue7551 which (when the steps to in the readme.md are followed) produces the code in question.

**Comment by sokra** [comment]
This is probably fixed by https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/308, but this PR is not yet released.

cc @evilebottnawi

**Comment by evilebottnawi** [comment]
@sokra yep, I still do not have the opportunity to publish new versions, I'm helpless here

**Comment by montogeek** [comment]
@evilebottnawi What is the problem exactly?

**Comment by montogeek** [comment]
@evilebottnawi I mean, to release the fix.

**Comment by evilebottnawi** [comment]
@montogeek i don't have npm access to release, and developers who should do release are unavailable around 1-2 month. I switch on own fork and looks it will be recommendation for all.

**Comment by montogeek** [comment]
@evilebottnawi Yeah, that sounds fine

**Comment by sokra** [comment]
you have access @evilebottnawi, at least the `evilebottnawi` on npm has access. Or isn't that you?

**Comment by evilebottnawi** [comment]
@sokra looks somebody give me access to npm :+1: today i will do release, thanks!

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/308
