### ISSUE TITLE
Webpack Watch change/rename detection of js to jsx, css to scss or / file to folder / index. [Ext]

### ISSUE THREAD

**Issue by FL0RIANMEYER** [webpack/webpack#7976]
# Bug report

**What is the current behavior?**
Webpack Watch has not detected any changes / renamings of js in jsx, css in scss or / file in folder / index. [Ext]

_ERROR in ./app/reducer/ui/setting.js
Module build failed: Error: ENOENT: no such file or directory_

**If the current behavior is a bug, please provide the steps to reproduce.**

Rename a file in watch mode (-w). Compilation does not work anymore. **Webpack process must be restarted** to fix new file detection.

**What is the expected behavior?**

Detect at least file extension changes (renames) of resolve.extensions prop from webpack.config.[babel].js:
```Javascript
{
    resolve: {
        extensions: ['.js', '.jsx'] // ['.css', '.scss']
   }
}
```
and 
changes of 
```Javascript
    import from '***/folder/file'
```
to
```Javascript
    import from '***/folder/folder/index.[resolve.extensions]'
```

**Other relevant information:**
webpack version:  4.17.1

Node.js version: 10.7.0
Operating System: Win
Editor: Atom@1.30.0

**Comment by evilebottnawi** [comment]
@pitops shoyld be fixed in `webpack@5`

**Comment by pitops** [comment]
I see thank you @evilebottnawi

**Comment by lensbart** [comment]
@evilebottnawi The problem still exists, and also on macOS. I believe the issue is as follows: file renames are not recognised when both paths can be resolved via the same string. Some examples:

`./dir/file.jsx` —> `./dir/file/index.jsx` (both can be imported via `./dir/file`)
`./dir/file.jsx` —> `./dir/file.tsx` (Of course, both extensions need to be specified under `resolve` in the config file.) This one is particularly annoying when rewriting a project to TypeScript, requiring a complete rebuild so check if the project still compiles.
`./dir/file.scss` —> `./dir/file/index.scss` etc.

The problem happens reproducibly. I don’t think there’s anything special in our webpack config: `resolve: { extensions: ['.ts', '.tsx', '.mjs', '.js', '.jsx', '.json', '.scss'] }`

**Comment by lensbart** [comment]
Thanks for your service @webpack-bot but the issue still persists.

**Comment by evilebottnawi** [comment]
@lensbart fixed in webpack@5

**Comment by salemhilal** [comment]
@joebeachjoebeach and I ran into this issue recently (we can't upgraded to Webpack 5 quite yet). We found that this was a problem with the resolver's `unsafeCache`. It looks like `resolve.unsafeCache` is [documented incorrectly, at least in the v4 docs](https://v4.webpack.js.org/configuration/resolve/#resolveunsafecache) — that value seems to be passed through to enhanced-resolve, which expects an object or a boolean (not a regex, as the documentation mentions).

If you provide `resolver.unsafeCache` with an object, enhanced-resolve will use that object as its own cache. This means that you can supply a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) object instead of a regular one. We used the proxy object to check if a file existed on disk before returning a cache value. This adds IO, but surprisingly didn't impact build times by as much as we thought it might. 

You can also disable this cache entirely, but it caused recompilations for us to be much slower. For some timing data, a partial rebuild of a somewhat large React app took as high as 45 seconds, whereas enabling the cache brought a rebuild down to around 2 or 3 seconds. 

To wrap that all up, we fixed this problem, without incurring too much of a perf hit, like this:
```js
const realUnsafeCache = {};
const unsafeCacheHandler = {
    get(cache, key) {
        const cachedValue = cache[key];

        // make sure the file exists on disk
        if (cachedValue && !fs.existsSync(cachedValue.path)) {
            // and if it doesn't, evict that cache entry.
            delete cache[key];
            return undefined;
        }

        return cachedValue;
    },
};
const theProxiedCache = new Proxy(realUnsafeCache, unsafeCacheHandler);

// and in our config:
resolve: {
    unsafeCache: theProxiedCache,
}
```
