### ISSUE TITLE
Rule with issuer is not applied when importing via require.context

### ISSUE THREAD

**Issue by andrey-skl** [webpack/webpack#9309]
# Bug report

**What is the current behavior?**
Loaders are not applied for files, imported via `require.context`, if rule has "issuer" option.

**If the current behavior is a bug, please provide the steps to reproduce.**
See reproduction https://github.com/huston007/webpack-issuer-repro

In short:
In webpack.config:
```
rules: [
      {
        test: /\.svg/,
        issuer: /\.js/, // Remove this line and everything works
        loader: 'url-loader'
      }
    ]
```

a.js:
```
function importAll (r) {
  r.keys().forEach(r);
}

importAll(require.context('.', false, /\.svg$/));
```

Build error:
```
WARNING in ./circle.svg 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><circle cx="8" cy="8" r="8"/></svg>
 @ . sync nonrecursive \.svg$ ./circle.svg
 @ ./a.js
```

Note that it is doesn't matter what is inside ["issuer"](https://github.com/huston007/webpack-issuer-repro/blob/master/webpack.config.js#L9) property.
It also breaks if using wildcarded require like `require('./'+fileName+'.svg')`

**What is the expected behavior?**
Loaders are applied in-spite of a way how file is imported: via direct require or via context.

**Known workaround**
It is possible to workaround by inlining loader syntax like: `require.context('!file-loader!./', true, /\.svg$/)`

**Other relevant information:**
webpack version:  4.35.0
Node.js version: 10.15.0
Operating System: macOS

Maybe related to #6915

**Comment by evilebottnawi** [comment]
Looks like a bug, PR welcome

**Comment by Odrin** [comment]
Same problem with ``import(`./${icon}.svg`)`` and ``require(`./${icon}.svg`)``
My config:
```
{
  test: /\.svg$/,
  issuer: /\.jsx?$/,
  use: [
    { loader: '@svgr/webpack' },
  ],
},
```

**Comment by evilebottnawi** [comment]
bump

**Comment by benjaminpreiss** [comment]
Same problem for me.

**webpack.config.js**:

```js
      {
        test: /index\.html$/,
        use: [
            {
              loader: 'file-loader',
              options: {
                // specifies output path relative to output.path
                outputPath: './',
                name: '[name].[ext]',
              },
            },
            "extract-loader",
            {
              loader: "html-loader",
              options: {
                  attributes: {
                    list: [
                      {
                        tag: 'link',
                        attribute: 'href',
                        type: 'src',
                      }
                    ],
                  },
              }
            }
        ]
      },
      {
        test: /\.(sa|sc)ss$/,
        use: (info) => ([
          {
            loader: 'file-loader',
            options: {
              esModule: false,
              name: '[contenthash].css',
              outputPath: 'css',
              publicPath: path.basename(info.issuer) === 'index.html' ? './css/' : '../css/',
            }
          },
          {
            loader: 'extract-loader',
          },
          {
            loader: 'css-loader'
          },
          {
            loader: 'postcss-loader'
          },
          {
            loader: 'sass-loader',
            options: {
              implementation: require("sass")
            }
          }
        ]),
      }
```

**index.html**:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    ...
    <link rel="stylesheet" type="text/css" href="../scss/index.scss">
</head>
<body>
</body>
</html>
```

Running `npx webpack` I get:

```
The "path" argument must be of type string. Received null
```

**Comment by stefanprobst** [comment]
i think this is still an issue. there's also an unreviewed PR #10362 for it.

**Comment by antalutrazvan** [comment]
What is the status on this guys ?
For webpack `4.42.0` this is still an issue :(

**Comment by panlina** [comment]
Still an issue on 4.46. Any plan to fix it?

**Comment by alexander-akait** [comment]
Only webpack v5

**Comment by panlina** [comment]
> Only webpack v5

Can't this be fixed in v4?

**Comment by alexander-akait** [comment]
No, v4 only security fixes

**Comment by lzl124631x** [comment]
Bump. Still facing this issue when loading svg from different extensions like tsx or less.

**Comment by KODerFunk** [comment]
Bump. Still facing this issue when loading fonts for preloading by env from different folders.

**Comment by alexander-akait** [comment]
There is note why it is not easy https://github.com/webpack/webpack/pull/10362#issuecomment-674068381, but anyway it is solvable

**Comment by ekkis** [comment]
`npm webpack --version` yields 8.18.0 but I think I'm also suffering from this bug as it relates to https://github.com/vercel/next.js/discussions/15437

**Comment by Ekagrashharma** [comment]
Is this bug fixed?
